[GPU] Add flag to monitor GPU memory usage
openxla/xla pull request #10238
Opened 2024-03-04 23:19 UTC by trevor-m

This PR adds the flag `--xla_gpu_memory_monitoring_level`. The default value is 0, which disables the feature.
A value of 1 will add warnings when GPU memory usage crosses 95% of the total available memory.
A value of 2 will additionally report the memory usage every 10 seconds.

Currently, the monitoring thread is created when the PJRT client is created. However if there is a better place to do this then any advice would be appreciated.

2024-03-05 12:33 UTC, dimitar-asenov approved these changes

2024-03-05 18:42 UTC, trevor-m commented on xla/xla.proto
> +  // Level of GPU memory monitoring.
Thank you @dimitar-asenov for the review! Done.

2024-03-06 08:59 UTC, cheshire commented
Is it possible to explain the motivation a bit more? Ideally, XLA shouldn't do any allocations at all during the runtime? Also how does this interplay with the BFC allocator?

2024-03-06 18:00 UTC, trevor-m commented
> Is it possible to explain the motivation a bit more? Ideally, XLA shouldn't do any allocations at all during the runtime? Also how does this interplay with the BFC allocator?

Hi @cheshire. The allocations at runtime are coming from Nvidia libraries which take memory outside of the BFC allocator. Primarily we are looking at NCCL communicators since they use a lot of memory, but cublas and cudnn also allocate some too.

Perhaps this monitoring should be targeted specifically at those areas instead? For example, I could log the memory usage every time a communicator is created.

2024-03-08 13:22 UTC, cheshire requested changes
Would like to have a more fine-grained solution, as normally XLA shouldn't allocate memory at runtime.

2024-03-11 05:36 UTC, kamaljeeti commented
Hi @trevor-m , can you have a look at the comments? Thanks

2024-03-11 16:50 UTC, trevor-m commented
Hi @cheshire, while it would be ideal if XLA can control all of the memory allocated by third party libraries, the current situation is that we cannot and are facing lots of memory related issues. Having this small tracker in XLA would make it easier to detect these problems and measure improvements over time without requiring external profiling tools.

2024-03-12 10:45 UTC, dimitar-asenov commented
@trevor-m: We are concerned about potential confusion this code may cause.

Generally, it's desirable that XLA does not allocate any memory at run-time. In most cases today there are indeed only static allocations and XLA users have an expectation that memory is unchanging at run-time. If we add this code the new flag will be a strong signal that memory is not static and may change. This conflicts with the users' expectations and is confusing. 

On the other hand, the reality of NCCL is that it indeed allocates a lot of memory at run-time. We don't want to have our head in the sand so it's useful to expose this.

Here is a path forward, assuming that run-time memory allocations other than NCCL are insignificant (@cheshire @trevor-m is this assumption reasonable?):

- Let's clarify what XLA use-cases will benefit from this feature. Do you have 2-3 concrete examples where you want to apply this? If not, perhaps it's not worth it.
- To avoid the confusion for all the non-NCCL use-cases, can we expose this feature only for NCCL? Is it possible to differentiate between the different sources of run-time memory allocation (NCCL vs others)?
  - If yes, and the use-cases we have in mind are all about NCCL, let's just measure NCCL and expose the feature with the appropriate names.
  - If not, and we're fairly certain that NCCL is the dominant run-time memory allocator, then we could still expose this feature as if it's focused on NCCL. We can clarify in comments that this may measure some additional memory. 
- If there is a way to add this measurement without a flag, so that it's always on, that might be preferable. The requirements are
  1. the impact on performance is imperceptible (can't judge if this is the case for the current code).
  2. there aren't excessively many log entries (should be satisfied already).

2024-03-25 17:42 UTC, trevor-m commented
> @trevor-m: We are concerned about potential confusion this code may cause.
> 
> Generally, it's desirable that XLA does not allocate any memory at run-time. In most cases today there are indeed only static allocations and XLA users have an expectation that memory is unchanging at run-time. If we add this code the new flag will be a strong signal that memory is not static and may change. This conflicts with the users' expectations and is confusing.
> 
> On the other hand, the reality of NCCL is that it indeed allocates a lot of memory at run-time. We don't want to have our head in the sand so it's useful to expose this.
> 
> Here is a path forward, assuming that run-time memory allocations other than NCCL are insignificant (@cheshire @trevor-m is this assumption reasonable?):
> 
> * Let's clarify what XLA use-cases will benefit from this feature. Do you have 2-3 concrete examples where you want to apply this? If not, perhaps it's not worth it.
> * To avoid the confusion for all the non-NCCL use-cases, can we expose this feature only for NCCL? Is it possible to differentiate between the different sources of run-time memory allocation (NCCL vs others)?
>   
>   * If yes, and the use-cases we have in mind are all about NCCL, let's just measure NCCL and expose the feature with the appropriate names.
>   * If not, and we're fairly certain that NCCL is the dominant run-time memory allocator, then we could still expose this feature as if it's focused on NCCL. We can clarify in comments that this may measure some additional memory.
> * If there is a way to add this measurement without a flag, so that it's always on, that might be preferable. The requirements are
>   
>   1. the impact on performance is imperceptible (can't judge if this is the case for the current code).
>   2. there aren't excessively many log entries (should be satisfied already).

Thanks @dimitar-asenov for the comments. I'm going to close this for now and see if I can rework it to something better or if we can avoid it entirely for our use cases.

2024-03-25 17:42 UTC, closed without merging