Split FP8 And Non-FP8 GEMM Rewriters
openxla/xla pull request #10390
Opened 2024-03-09 01:20 UTC by philipphack

Separates the rewriters for FP8 and non-FP8 GEMMs and moves the rewrite of FP8 GEMMs ahead of the Triton GEMM rewriter.

2024-03-09 01:21 UTC, philipphack commented
CC @reedwm.

2024-03-11 23:02 UTC, reedwm requested changes

2024-03-11 23:02 UTC, reedwm commented on xla/service/gpu/tests/gemm_rewrite_test.cc
> +      hlo_text, GemmRewriter(GpuComputeComp(), /*f8_rewrite=*/false),
Shouldn't you pass f8_rewrite=true here?

2024-03-12 01:46 UTC, reedwm approved these changes

2024-03-12 05:12 UTC, closed without merging