Dummy AllocateBuffer implementation
openxla/xla pull request #10638
Opened 2024-03-16 08:07 UTC by jaro-sevcik

The runtime takes care of allocating the buffer, so the allocation is a no-op.

2024-04-11 13:29 UTC, jaro-sevcik commented
Here is a link to a motivation/summary doc: https://docs.google.com/document/d/12LjzvR0foAMnkB7p7-EtiuwdhfmsRAsEWYFTGGiOs7U/edit?usp=sharing

2024-04-12 08:07 UTC, jaro-sevcik commented
Let me know if you think this needs a test in XLA (this will be eventually tested via JAX because host-offloading in the remat-scan test introduces the "AllocateBuffer" op).

2024-04-19 15:33 UTC, cheshire commented
And otherwise, HLO with this custom call would crash now? Then it would be possible to write a test?

2024-04-24 16:57 UTC, cheshire requested changes

2024-04-24 18:25 UTC, jaro-sevcik commented on xla/service/gpu/tests/allocate_buffer_custom_call_test.cc
> +class AllocateBufferTest : public HloTestBase {};
Done (even though the test is about the allocation aspect of the custom call, so I find the "nop" somewhat misleading)

2024-04-25 16:42 UTC, cheshire approved these changes

2024-04-25 18:34 UTC, closed without merging