[XLA:CPU] Bug fix for enabling F16 support
openxla/xla pull request #10930
Opened 2024-03-25 23:40 UTC by kanvi-nervana

This PR fixes a bug for f16 matmul enabling.
Since dot is supported in f16, there is no need for adding an extra convert instruction after fusion similar to the bf16 case.
Also add missed changes in build file.

2024-03-26 13:47 UTC, penpornk requested changes
Thank you for the PR!

2024-03-26 13:47 UTC, penpornk commented on xla/service/cpu/onednn_matmul_rewriter.cc
>        // for bf16 case to avoid datatype mismatch.
Please update the comment here as well (that convert for bf16 is optional now).

2024-03-27 17:25 UTC, kanvi-nervana commented
@penpornk I have addressed the comment.

2024-03-27 18:38 UTC, penpornk approved these changes
Thank you for the change!

2024-03-28 01:21 UTC, closed without merging