[ROCM] Updated fp8 matmul with adjustments for updated hipBlasLt support in ROCm 6.2
openxla/xla pull request #12928
Opened 2024-05-22 04:40 UTC by wenchenvincent

Main changes include:
* Added support for fp8 matmul with output data type to be fp8 and bf16.
* Added buffer comparators for fp8e4m3fnuz and fp8e5m2fnuz

2024-06-20 01:23 UTC, wenchenvincent commented
@reedwm Could you kindly take a look at this PR? Thanks!

2024-06-21 01:00 UTC, reedwm requested changes

2024-06-21 01:38 UTC, wenchenvincent commented on xla/service/gpu/gemm_rewriter.cc
>        case F8E4M3FN:
I agree. Before adding that, I have a question: `gemm_rewriter.cc` was refactored to get rid of those `GOOGLE_CUDA` and `TENSORFLOW_USE_ROCM` compile-time macros and use runtime checks of `gpu_version_` and `toolkit_version_`. I followed the new style mostly except here, as using the runtime checks of `gpu_version` and `toolkit_version_` might make the code a bit more duplicated here. What's your opinion about this?

2024-06-21 01:56 UTC, reedwm commented on xla/service/gpu/gemm_rewriter.cc
>        case F8E4M3FN:
Ah I didn't realize GOOGLE_CUDA and TENSORFLOW_USE_ROCM are no longer used. I would continue to not use them. But yeah, this does make writing the switch statement a bit tricky.

I would replace the switch statement with an if-statement. Do something like:

```c++
PrimitiveType d_type = instr->shape().element_type();
bool supported_d_type = d_type == BF16 || d_type == F16 || d_type == F32;
if ((IsCuda() && (d_type == F8E4M3FN || d_type == F8E5M2)) {
  supported_d_dtype = true
}
if ((IsRocm() && rocm_version >= 60200 && (d_type == F8E4M3FNUZ || d_type == F8E5M2FNUZ)) {
  supported_dtype = true
}
If (!supported_dtype) {
  // VLOG and return false
}
```

Alternatively, the switch-statement can be kept by using fallthrough: Only break in the F8E4M3FNUZ and F8E5M2FNUZ case if a supported rocm version is used.

2024-06-21 03:59 UTC, wenchenvincent commented on xla/service/gpu/gemm_rewriter.cc
>        case F8E4M3FN:
Thanks! I think the if-statement is clearer and just changed to it.

2024-06-21 17:32 UTC, reedwm approved these changes

2024-06-21 19:42 UTC, closed without merging