Fix _xla_send_recv_validation_attribute in loop-double-buffer-transfo…
openxla/xla pull request #13278
Opened 2024-05-31 18:45 UTC by shraiysh

…rmer

This patch fixes the value of valid iteration for GPUs in the loop-double-buffer-transformer pass.

If the original iteration bounds for a particular GPU are {a,b} then the transformed attribute is:
  - If number of iterations is even: - For collective.permute.1: {floor((a+1)/2), floor(b/2)} - For collective.permute.2: {floor(a/2), max(0, floor((b-1)/2))}
  - If the number of iterations is odd: then the first iteration is peeled out
    - For collective.permute.1: {floor(a/2), max(0, floor((b-1)/2))}
    - For collective.permute.2: {max(0, floor((a-1)/2)), max(0, floor((b-2)/2)} For collective.permute.peeled:
  - If it is a forward cycle, then the attribute is {{0,0}, {1,0}, {1,0}, ...} i.e. only valid for the first device.
  - If it is a backward cycle, then the attribute is {{1,0}, {1,0}, ..., {1,0}, {0,0}} i.e. only valid for the last device.

More details about reasoning for this are [here](https://docs.google.com/document/d/1piacngohC8ZIRXL9Dmx42mczgeOZb3x5lVlhLYIr-p8/)

2024-06-04 09:21 UTC, cheshire commented
> More details about reasoning for this are [here](https://docs.google.com/document/d/1piacngohC8ZIRXL9Dmx42mczgeOZb3x5lVlhLYIr-p8/)

Why not bring it in as an extended comment? We like those!

2024-06-04 09:26 UTC, cheshire requested changes

2024-06-04 09:26 UTC, cheshire commented on xla/service/gpu/double_buffer_loop_unrolling.cc
> +    std::basic_string<char>& str) {
Nit: basic_string is a bit unusual, maybe absl::string_view?

2024-06-04 09:26 UTC, cheshire commented on xla/service/gpu/double_buffer_loop_unrolling.cc
> +absl::StatusOr<std::vector<std::pair<int64_t, int64_t>>> ParseVectorOfPairs(
Nit: pair<int64, int64> occurs quite a few times below, maybe do

`using Interval = pair<int64, int64>` ?

2024-06-04 09:26 UTC, cheshire commented on xla/service/gpu/double_buffer_loop_unrolling.cc
> +absl::StatusOr<std::vector<std::pair<int64_t, int64_t>>> ParseVectorOfPairs(
Docstring?

2024-06-04 09:26 UTC, cheshire commented on xla/service/gpu/double_buffer_loop_unrolling.cc
> +  assert(new_instr->opcode() == old_instr->opcode() &&
We do not use `assert` inside, either CHECK if you want to crash the whole process (very rare) or TF_RET_CHECK to return Status.

2024-06-04 09:26 UTC, cheshire commented on xla/service/gpu/double_buffer_loop_unrolling.cc
> +  google::protobuf::Map<std::string, std::string> attribute_map =
const ref?

2024-06-04 09:26 UTC, cheshire commented on xla/service/gpu/double_buffer_loop_unrolling.cc
> +  if (is_forward_cycle)
Nit: please add braces, here and below.

2024-06-04 09:26 UTC, cheshire commented on xla/service/gpu/double_buffer_loop_unrolling.cc
> +absl::Status SetSendRecvValidationForPeeledInstr(HloInstruction* new_instr,
Please add docstrings.

2024-06-04 09:26 UTC, cheshire commented on xla/service/gpu/double_buffer_loop_unrolling.cc
> +  for (std::pair<int64_t, int64_t> pair : send_recv_validation_attr) {
Nit: const ref, here and below/above.

2024-06-04 09:26 UTC, cheshire commented on xla/service/gpu/double_buffer_loop_unrolling_test.cc
> +  EXPECT_EQ(collective_permutes[1]->frontend_attributes().map().at(
Nit: maybe do a FileCheck test to give an easier at-a-glance representation of what happens to IR?

2024-06-05 11:50 UTC, tdanyluk commented
I'm deferring to cheshire@ on this one.

2024-06-10 06:11 UTC, shraiysh commented
> Why not bring it in as an extended comment? We like those!

I added more details along with examples in the docstrings for the functions. I have also tried to address all your comments. Requesting review again.

2024-06-10 15:39 UTC, frgossen reviewed
Looks very good. A few minor comments.

2024-06-10 15:39 UTC, frgossen commented on xla/service/gpu/double_buffer_loop_unrolling.cc
> +  std::string iteration_instances_new_instr1 =
This serialization appears twice here and also above. Extract as a function?

2024-06-10 15:39 UTC, frgossen commented on xla/service/gpu/double_buffer_loop_unrolling.cc
> +  std::string send_recv_validation_attr_str =
This logica can be shared with below.

2024-06-10 15:39 UTC, frgossen commented on xla/service/gpu/double_buffer_loop_unrolling.cc
> +  // Do the same for new instr
This looks similar. Can you extraxt this into a function `CopyAttributes` with a skip_key param. 
Or something like that..

2024-06-11 20:05 UTC, shraiysh commented
Addressed comments. Requesting review again @frgossen @cheshire.

2024-06-12 15:41 UTC, frgossen approved these changes
Thanks!

2024-06-12 17:08 UTC, frgossen commented
double_buffer_loop_unrolling.cc fails to build. 
Error: error: no template named 'Map' in namespace 'google::protobuf'
  122 |   const google::protobuf::Map<std::string, std::string>& attribute_map =

2024-06-12 20:04 UTC, shraiysh commented
I changed that to `const auto&`. Hopefully that'll use the right type.

2024-06-13 08:26 UTC, golechwierowicz approved these changes

2024-06-13 10:27 UTC, closed without merging