Fix _xla_send_recv_validation in collective pipeliner
openxla/xla pull request #13555
Opened 2024-06-09 17:43 UTC by shraiysh

This patch fixes the `_xla_send_recv_validation` attribute in collective pipeliner.

When the pipelining direction is forward:

 - For the peeled collective (after the while loop): it should only run for the last GPU, once. Hence the attribute is `{{1,0},{1,0},{1,0},{0,0}}`.
 - For the collective within loop: the trip count reduces by one but the last iteration is the one that is peeled. So, the iteration numbers of all the GPUs are unaffected except the last GPU. The upper bound of the last GPU gets decremented by one. For example, `{{0,6},{1,7},{2,8},{3,9}}` changes to `{{0,6},{1,7},{2,8},{3,8}}`.

When the pipelining direction is backward:

 - For the peeled collective (before the while loop): it should only run once for the first GPU. Hence the attribute is `{{0,0},{1,0},{1,0},{1,0}}`.
 - For the collective within loop: the trip count reduces by one but the first collective is the one that is peeled. So, the iteration numbers of all the GPUs (both upper bound and lower bound) reduce by one. For example, `{{0,6},{1,7},{2,8},{3,9}}` changes to `{{0,5},{0,6},{1,7},{2,8}}`.

The pipelining direction `kForwardSink` is not expected to have this attribute.

2024-06-11 17:41 UTC, frgossen requested changes
How does this relate to your previous PR 12892? What aspect does it fix?

2024-06-11 17:41 UTC, frgossen requested changes

2024-06-11 17:41 UTC, frgossen commented on xla/service/collective_pipeliner.cc
> +  std::string send_recv_validation_attr_str =
This appears in multiple PRs. Can you extract it as a function and reuse it?

2024-06-11 20:11 UTC, shraiysh commented
> How does this relate to your previous PR 12892? What aspect does it fix?

This is not about fixing a logical issue in the code. This fixes the value of the attribute when collective pipeliner is run. Collective pipeliner peels one iteration, where the peeled collective ends up before (or after) the loop if the pipelining direction is backward (or forward). This means that there is one less iteration and so the "valid iterations" should reflect that change. The peeled collective should also have a proper annotation indicating which device should run it.

On a related note, can you add @bixia1 as a review too? I think it would be good if she could check the testcases and give a go ahead for this fix.

2024-06-11 20:24 UTC, shraiysh commented
I think I need to fix the logic in this a bit. Converting to draft for sometime while I figure this out.

2024-06-12 20:05 UTC, shraiysh commented
This is ready for review now @bixia1 @frgossen

2024-06-18 16:52 UTC, frgossen approved these changes
Thanks!

2024-06-18 16:53 UTC, frgossen commented
This needs another rebase to pass the internal CI

2024-06-18 17:22 UTC, shraiysh commented
>This needs another rebase to pass the internal CI

Done. Thanks for the review!

2024-06-18 20:59 UTC, bixia1 approved these changes

2024-06-19 16:46 UTC, shraiysh commented
@frgossen any ideas why this isn't going through? The CI build failure seems unrelated.

2024-06-20 06:29 UTC, akuegel approved these changes

2024-06-20 06:35 UTC, akuegel commented
It looks like somehow the approval of @bixia1 didn't count. I approved again.

2024-06-20 12:08 UTC, closed without merging