[ROCm] Fix pjrt topology code to support ROCm
openxla/xla pull request #13805
Opened 2024-06-14 23:12 UTC by Ruturaj4

2024-06-24 18:00 UTC, jyingl3 approved these changes

2024-06-25 00:19 UTC, jyingl3 commented
The head has some recent change. Do you mind merge the conflicts with the head? Thanks!

2024-06-25 16:10 UTC, jyingl3 approved these changes

2024-06-26 00:26 UTC, reedwm requested changes
Is it possible to add a test? Our internal presubmits now require all changes to have tests, or requires a very good reason why no test is necessary.

2024-06-26 00:26 UTC, reedwm commented on xla/pjrt/c/pjrt_c_api_gpu_internal.cc
> +      (PJRT_GPU_PLUGIN_PLATFORM_NAME == "ROCM") ? xla::RocmId() : xla::CudaId();
`PJRT_GPU_PLUGIN_PLATFORM_NAME` is a string literal (e.g. `"ROCM"`) and comparing two string literals with == doesn't necessarily work. Convert `PJRT_GPU_PLUGIN_PLATFORM_NAME` to a string or string view, e.g. `std::string(PJRT_GPU_PLUGIN_PLATFORM_NAME) == "ROCM"`

2024-07-02 20:38 UTC, jyingl3 approved these changes

2024-07-03 08:56 UTC, closed without merging