Fix PadEmptyTensor pattern to return success()
openxla/xla pull request #14086
Opened 2024-06-23 06:37 UTC by apivovarov

Currently, the `PadEmptyTensor` and `DynamicPadEmptyTensor` patterns incorrectly return `failure()` after `rewriter.replaceOpWithNewOp`. This appears to be a typo, as the usual practice is to return `success()` following `rewriter.replaceOpWithNewOp`.

2024-06-24 11:20 UTC, d0k approved these changes

2024-06-25 19:27 UTC, apivovarov commented
Just want to check if this PR is ready to be merged? @d0k @penpornk

2024-06-27 17:25 UTC, apivovarov commented
Benjamin, Penporn, Can you look at this PR? It seems to be stuck. I think it is ready to be merged. @d0k @penpornk

2024-06-27 20:01 UTC, d0k approved these changes

2024-06-27 20:01 UTC, d0k commented
Looks like my approval isn't enough somehow? @penpornk do you know what's going on?

2024-06-28 06:57 UTC, apivovarov commented
I just rebased this PR branch from the latest main

2024-06-28 07:26 UTC, akuegel commented
I wonder whether it is possible to test this? Maybe we didn't have any test coverage for this pattern?

2024-06-28 07:30 UTC, reedwm requested changes
We have  a presubmit that requires all changes have a test, or a justification for why no test is needed. Can a test be added?

Also any ideas why this is not already failing a test (or a real model)? I would expect returning `failure()` would cause something to fail. @d0k do you know

2024-06-28 07:30 UTC, reedwm commented
Ah @akuegel commented the same thing as I did right before me :)

2024-06-28 07:41 UTC, akuegel commented
> I wonder whether it is possible to test this? Maybe we didn't have any test coverage for this pattern?

I just checked, the test coverage is through https://github.com/openxla/xla/blob/main/xla/mlir_hlo/tests/Dialect/mhlo/canonicalize/canonicalize.mlir#L2362

This really executes the code, but somehow the test doesn't fail although we return failure. So that indicates that it may be difficult to test this behavior change.

2024-06-28 07:45 UTC, akuegel commented
> > I wonder whether it is possible to test this? Maybe we didn't have any test coverage for this pattern?
> 
> I just checked, the test coverage is through https://github.com/openxla/xla/blob/main/xla/mlir_hlo/tests/Dialect/mhlo/canonicalize/canonicalize.mlir#L2362
> 
> This really executes the code, but somehow the test doesn't fail although we return failure. So that indicates that it may be difficult to test this behavior change.

I have asked in our mlir chat room what is going on here. Maybe someone knows.

2024-06-28 19:09 UTC, reedwm commented
From the chat thread, it seems testing cannot be done without creating C++ code to run the pass. I don't think it's worth trying to test this, considering this change has no functional impact, and AFAIK it's very common to test passes via MLIR files without testing whether the pass returns success() vs failure(). I'll try merging.

2024-06-28 21:33 UTC, closed without merging