Fix build issue in xla/hlo/utils/hlo_sharding_util_test.cc
openxla/xla pull request #14255
Opened 2024-06-27 22:37 UTC by apivovarov

This PR fixes the following build error in `xla/hlo/utils/hlo_sharding_util_test.cc` (used GCC-13):
```bash
xla/hlo/utils/hlo_sharding_util_test.cc:538:41: error: call of overloaded 'TileAssignment(<brace-enclosed initializer list>)' is ambiguous
  538 |   TileAssignment tile_assignment({16, 4});
```

2024-06-28 07:39 UTC, apivovarov commented
@akuegel Can you look at this build fix?

2024-06-28 07:45 UTC, reedwm requested changes
Interesting, I can reproduce this with https://godbolt.org/z/MonhYaYzb. clang compiles this, but gcc complains. I wonder which compiler is right.

Anyway, I prefer adding a `TileAssignment` constructor taking a `std::initializer_list<int64_t>`:

```c++
explicit TileAssignment(std::initializer_list<int64_t> dims) : 
    TileAssignment(absl::Span<const int64_t>(dims)) {}
```

I think this will allow constructing TileAssignment like `TileAssignment({4, 1})`, which might be accidentally done in the future since we don't test with gcc.

2024-06-28 07:45 UTC, reedwm commented
Also the build failure is spurious, ignore it.

2024-06-29 03:54 UTC, apivovarov commented
- Added `TileAssignment(initializer_list)` constructor
- Replaced `TileAssignment((absl::Span<const int64_t>){a, b})` with `TileAssignment({a, b})`.

2024-07-02 19:59 UTC, apivovarov commented
Looks like this PR got lost. @reedwm

2024-07-03 06:05 UTC, akuegel approved these changes

2024-07-03 10:20 UTC, closed without merging