[XLA:GPU] use empty cuda-graph node as command buffer barrier node for CUDA_VERSION >= 12040
openxla/xla pull request #14458
Opened 2024-07-05 01:36 UTC by shawnwang18

tested that cuda_12.4 have fixed the cuda graph issue that empty node can not be in conditioanl operator's sub-graph.

2024-07-08 12:05 UTC, cheshire requested changes
Any way we could test this?

2024-07-08 14:08 UTC, shawnwang18 commented
> Any way we could test this?

I think running existing tests with cuda 12.4 should test it. For example: test https://github.com/openxla/xla/blob/d2d668321c5507a9563fc3a77a0a7a62de4e1a93/xla/service/gpu/runtime/command_buffer_thunk_test.cc#L849 should cover this case. 

google's CI currently uses 12.3?  can we also add new cuda release?

2024-07-08 15:45 UTC, ezhulenev approved these changes

2024-07-09 04:10 UTC, NaiyerRizz approved these changes

2024-07-09 04:28 UTC, ezhulenev approved these changes

2024-07-09 15:56 UTC, closed without merging