Fix while loop parsing in in protobuf format
openxla/xla pull request #14476
Opened 2024-07-05 20:57 UTC by shraiysh

While loop computations were not being linked to the while operation. This patch fixes that and connects them.

2024-07-08 14:37 UTC, frgossen requested changes
Can you add a test case?

2024-07-08 14:38 UTC, shraiysh commented
Do you know where testcases for this would be added?

2024-07-08 18:26 UTC, frgossen commented
> Do you know where testcases for this would be added?

hlo_parser_test.cc

2024-07-08 18:42 UTC, shraiysh commented
@frgossen modified tests to check for this too.

2024-07-08 19:18 UTC, frgossen requested changes
I looked a bit more and think the parser should actually not populate this because it is ambiguous.

Example: For a computation that is used as a body for two distinct while ops, there is no way to populate this field correctly. With this change, you will just override it and keep the last one which is at least misleading. This field can only be populated correctly after flattening the call graph.

This field is populated in `xla/service/flatten_call_graph.cc` together with other caller/callee pointers.

2024-07-08 19:21 UTC, frgossen requested changes

2024-07-08 19:21 UTC, frgossen commented on xla/service/hlo_parser_test.cc
> +    for (HloComputation* computation : module->computations()) {
I don't think this is the right place to add an assertion. 
Can you add a test below to make sure that the field is null after parsing?

2024-07-08 19:53 UTC, shraiysh commented
I understand the concern, however, this is also done while [parsing HLO as text](https://github.com/openxla/xla/blob/15a888968d354c92b34d0d04cd962e8883ab4275/xla/service/hlo_parser.cc#L2155). The CreateWhileOp call sets this. I think we should fix that too in this case. Another thing is that some execution (for example, [address computation fusion here](https://github.com/openxla/xla/blob/15a888968d354c92b34d0d04cd962e8883ab4275/xla/service/gpu/fusions/custom.cc#L179) depend on this being already set up. Does this mean that we should run call graph flattening everytime we parse HLO even if it is already optimized?

2024-07-08 20:08 UTC, frgossen commented
@akuegel , you approved https://github.com/openxla/xla/pull/7179. Do you know what is the right thing to do here? 
- Populate the field and be aware that it could be ambiguous 
- Not populate it

2024-07-09 12:30 UTC, akuegel commented
> @akuegel , you approved #7179. Do you know what is the right thing to do here?
> 
> * Populate the field and be aware that it could be ambiguous
> * Not populate it

Yes, I approved it, and also suggested to use a back pointer. I was not aware of the difficulties with adding back pointers. We have an internal bug open for this. Not only while is affected, other ops with back pointers are potentially affected as well. Just for fusions we are on the safe side, because it is an op internal to XLA, so we control that there is always a 1:1 relationship between fusion instruction and fusion computation.

2024-07-10 18:25 UTC, frgossen approved these changes
Thanks@

2024-07-10 20:41 UTC, closed without merging