Skip emitting Triton kernel when deserializing from cache
openxla/xla pull request #15029
Opened 2024-07-17 18:27 UTC by jaro-sevcik

2024-07-19 14:26 UTC, bchetioui requested changes
Some small changes, but looks good, thanks!

2024-07-19 17:12 UTC, jaro-sevcik reviewed
Thank you for the review, the comments should be addressed now.

2024-07-20 16:30 UTC, bchetioui approved these changes
Thanks for addressing the comments!

2024-07-20 16:30 UTC, bchetioui commented on xla/service/gpu/gpu_aot_compilation_test.cc
> +  auto name =
We probably should---but that's out of scope for the current CL. Thanks for pointing it out!

2024-07-22 12:14 UTC, closed without merging