A better python API for accessing profiled instructions
openxla/xla pull request #15303
Opened 2024-07-25 07:49 UTC by yliu120

A previous PR https://github.com/openxla/xla/pull/15170 adds a python binding for accessing the profiled instruction.

Actually the API previously added contains repeated logic with `get_fdo_profile`, which works very similar as the added `get_instructions_profile`. The only difference is that `get_fdo_profile` writes to a string.

In essense, we only need to parse the proto to Python objects, if users really want to do so. 

This PR also adds a GPU test for the new API.

2024-07-25 07:52 UTC, yliu120 commented
@hawkinsp Sorry that before I have chance to add the test, the previous PR was merged.

I made a new PR that simply parse the proto and I guess we don't need to repeat xplane -> ProfiledInstructionsProto in many places. I also added a test to guard this API.

Thanks Peter.

2024-07-25 16:48 UTC, hawkinsp approved these changes

2024-07-25 17:18 UTC, yliu120 commented
Thanks. Just a note for the future outside-Google developer that needs to add tests for "no_oss" GPU tests.

I basically need to do,
1) comment out the "no_oss" tag
2) Add "xla_gpu_extension" and "gpu_plugin_deps" targets to the test target manually
3) Run `bazel test` with `--config=monolithic` to make it work.

2024-07-29 08:32 UTC, thomasjoerg requested changes

2024-07-29 08:32 UTC, thomasjoerg commented on xla/python/profiler.cc
> +  nb::class_<ProfiledInstruction> profiled_instruction_class(
When attempting to merge this PR, the internal CI at Google asked me to double-check that no updates to xla_extension/*.pyi type stub files were forgotten. Such updates may be required to  keep the type defs in sync with the code.

Can you please update type stub files are confirm that no updates are needed please?

2024-07-29 08:32 UTC, thomasjoerg commented on xla/python/profiler.cc
> +                       .instruction_name = c.name(), .cost_us = c.cost_us()});
Designated initializers are incompatible with C++ standards before C++20.
Please avoid them in the OpenXLA repo at the moment.

2024-08-08 15:56 UTC, penpornk commented
@yliu120 Could you please help address @thomasjoerg's comments?

2024-08-19 19:16 UTC, closed without merging

2024-08-19 19:19 UTC, yliu120 commented
Oh, sorry I haven't keep track this PR for a while.