[ROCm] Cleanup ir_emitter atomic support for ROCM
openxla/xla pull request #15357
Opened 2024-07-26 05:22 UTC by draganmladjenovic

Use a single instruction fp atomic intrinsic when possible. Support FP64 and BF16. Match atomic ordering to that of atomic* functions from HIP header.

Avoid usage of inttoptr in EmitAtomicOperationUsingCAS This alows the backend to select global atomic instruction and also enables SROA on cas_new_output.

2024-07-26 07:34 UTC, jreiffers commented
Thanks for your contribution. Just a heads up: this code path is essentially deprecated, so I'd recommend not spending any more effort on it. Investing in making the MLIR emitters work for AMD is definitely the better choice at this point.

2024-07-26 07:38 UTC, jreiffers requested changes

2024-07-26 07:38 UTC, jreiffers commented on xla/service/gpu/tests/gpu_atomic_test.cc
> +  CompileAndVerifyIr(std::move(module), is_built_with_rocm_ ? R"(
Nit: I think this is a bit more readable as

```
if (is_build_with_rocm_) {
  CompileAndVerifyIr
} else {
  CompileAndVerifyIr
}
```

(Assuming there's some reason why the separate test suite doesn't work).

2024-07-26 07:38 UTC, jreiffers commented on xla/service/gpu/tests/gpu_atomic_test.cc
> +  if (is_built_with_rocm_ &&
Let's create a separate test for AMD. I believe you should be able to use `GTEST_SKIP` in `SetUp` to prevent execution on Nvidia hardware then.

2024-07-26 07:38 UTC, jreiffers commented on xla/service/gpu/tests/gpu_atomic_test.cc
> +  HloModuleConfig config;
Can you add some comments to explain the purpose of this?

2024-07-26 07:38 UTC, jreiffers commented on xla/service/gpu/tests/gpu_atomic_test.cc
> +           .gfx9_mi200_or_later()) {
`has_fp64_atomics_support`

2024-07-26 07:38 UTC, jreiffers commented on xla/service/gpu/tests/gpu_atomic_test.cc
> +           .gfx9_mi100_or_later()) {
`has_fp32_atomics_support`

2024-07-26 07:38 UTC, jreiffers commented on xla/service/gpu/ir_emitter_nested.cc
> +  static bool no_paired_atomics = []() -> bool {
Let's name this `paired_atomics` and remove the negation where it's used.

2024-07-26 07:38 UTC, jreiffers commented on xla/service/gpu/ir_emitter_nested.cc
> +    const char* flag = std::getenv("ROCM_NO_PAIRED_ATOMICS");
I'm guessing this should be in `XLA_FLAGS`. If for some reason it can't, let's at least shorten this to `return flag && ...`.

2024-07-26 07:38 UTC, jreiffers commented on xla/service/gpu/ir_emitter_nested.cc
> +    source = builder->CreateBitCast(source, half2type);
The logic above here can probably use a comment or two.

2024-07-26 07:38 UTC, jreiffers commented on xla/service/gpu/ir_emitter_nested.cc
> +  return IsAMDGPU(module)
Probably more readable as an `if`.

2024-08-05 09:37 UTC, dimitar-asenov commented
@draganmladjenovic What is the state of this PR, do you still intend to merge it? Does the work on MLIR emitters obviate this PR? If you no longer intend to merge this PR (in favor of other work), please mark it as draft if you still need it for reference or close it altogether if you don't need it.

2024-08-05 10:45 UTC, draganmladjenovic commented
I plan to merge it. I still would make life easier for our downstream. Probably some time next week.

2024-09-16 14:01 UTC, dimitar-asenov commented
Hi @draganmladjenovic, could you please provide an update? Please consider making this PR a draft, in case you won't work on it in the near future. Thank you.

2024-11-11 15:42 UTC, dimitar-asenov commented
A lot of the code that this PR touches has been deleted. I'm closing it. If you need these changes implemented, please target the new MLIR-based emitters.

2024-11-11 15:42 UTC, closed without merging