[XLA:CPU][oneDNN] Prevent F32 fallback for BF16 rewritable dots
openxla/xla pull request #15776
Opened 2024-08-06 19:30 UTC by akhilgoe

This PR prevents some oneDNN rewritable BF16 dots from being converted to F32. In particular:
1. This PR prevents the oneDNN rewriter from performing layout checks before the layout assignment passes, thus avoiding the upcasting of dots with column-major layouts that might later be converted to row-major layouts.
2. In case the BF16 dots are not rewritable to oneDNN custom calls, this PR upcasts the BF16 dots to F32.
3. Currently, the oneDNN rewriter bypasses the layout checks for batch dots. This PR also introduces the layout checks for batch dots during the rewrite process.

2024-08-07 04:36 UTC, NaiyerRizz commented
Hi @akhilgoe 
Can you please see as few checks are failing.
Thank you

2024-08-07 10:25 UTC, penpornk requested changes
Thank you for the PR. Could you please add a test case for this?

2024-08-07 10:25 UTC, penpornk commented on xla/service/cpu/onednn_contraction_rewriter.cc
> +  // Skip row-major layout check before layout-pass
Nit:
```suggestion
  // Skip row-major layout check before layout-assignment pass
```

2024-08-07 10:25 UTC, penpornk commented on xla/service/cpu/onednn_contraction_rewriter.cc
>    // part of the layout-pass.
Nit:
```suggestion
  // Col-major layouts are corrected to row-major for BatchDot operation as
  // part of the layout-assignment pass.
```

2024-08-07 10:25 UTC, penpornk commented on xla/service/cpu/onednn_contraction_rewriter.cc
> +  // onednn custom calls.
Nit: 
```suggestion
  // oneDNN custom calls.
```

2024-08-07 23:05 UTC, akhilgoe commented
Thanks @NaiyerRizz for notifying me about the failing tests. I looked at the logs and I think the error might have been caused due to a missing rocm repository. I'll take a look again if the tests still fail.

2024-08-07 23:09 UTC, akhilgoe commented
Thanks @penpornk for the review! I think I have addressed all your comments. I also added a test that would fail without the changes in this PR. Please take a look.

2024-08-08 18:07 UTC, penpornk requested changes
Thank you for the quick response! I have two more nits please.

2024-08-08 18:07 UTC, penpornk commented on xla/service/cpu/tests/onednn_matmul_test.cc
> +}
Nit: Maybe split the checks to multiple lines using CHECK and CHECK-SAME? See lines 1494-1500 for examples.
E.g.,
```
; CHECK: (bf16[500,500]{1,0}, u8[{{.*}}]{0})
; CHECK-SAME: custom_call_target="__onednn$matmul"
```

2024-08-08 18:07 UTC, penpornk commented on xla/service/cpu/tests/onednn_matmul_test.cc
> +    ROOT dot.0 = bf16[500,500]{1,0} dot(arg.0, arg.1), lhs_contracting_dims={1}, rhs_contracting_dims={0}
Nit: Can we wrap this line so it's <= 80 characters long? Can simply do:
```suggestion
    ROOT dot.0 = bf16[500,500]{1,0} dot(arg.0, arg.1), lhs_contracting_dims={1},
      rhs_contracting_dims={0}
```

2024-08-08 18:18 UTC, akhilgoe commented
Thanks @penpornk! I have created a commit with your suggested changes.

2024-08-08 18:21 UTC, penpornk approved these changes
Thank you!
(Please help verify that the test still works? I made the suggestion without testing.)

2024-08-08 18:22 UTC, akhilgoe commented
Yes, I tested before pushing the commit.

2024-08-08 19:53 UTC, closed without merging