[XLA:GPU]add sycl_gpu_runtime and implement it to py_clinet_gpu
openxla/xla pull request #15905
Opened 2024-08-09 07:22 UTC by mayuyuace

2024-08-09 10:33 UTC, mayuyuace commented
What this error means?: "ERROR: Failed to init auth credentials: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information."

2024-08-09 10:55 UTC, penpornk reviewed
> What this error means?: "ERROR: Failed to init auth credentials: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information."

This is from [JAX Linux CPU](https://btx.cloud.google.com/invocations/6af16e78-eaa1-4cad-98f6-5199a7357d14/log) CI, right? It's just a CI infra error and is unrelated to this PR.

The [XLA Linux CPU](https://btx.cloud.google.com/invocations/de4aa5e1-4058-4370-a4fb-1c3b36c7fb6c/targets/tensorflow%2Fxla%2Flinux%2Fcpu%2Fbuild_cpu/log) CI has related errors though. Other targets should be able to build, with or without `--config=sycl`.

2024-08-12 02:40 UTC, mayuyuace commented
> > What this error means?: "ERROR: Failed to init auth credentials: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information."
> 
> This is from [JAX Linux CPU](https://btx.cloud.google.com/invocations/6af16e78-eaa1-4cad-98f6-5199a7357d14/log) CI, right? It's just a CI infra error and is unrelated to this PR.
> 
> The [XLA Linux CPU](https://btx.cloud.google.com/invocations/de4aa5e1-4058-4370-a4fb-1c3b36c7fb6c/targets/tensorflow%2Fxla%2Flinux%2Fcpu%2Fbuild_cpu/log) CI has related errors though. Other targets should be able to build, with or without `--config=sycl`.

Thank you for your reply. I have added SYCL compilation constraints to the newly added compilation target. I would like to know if any added compilation targets will be checked for compilation even if they are not used elsewhere.

2024-08-12 02:55 UTC, mayuyuace commented
> > What this error means?: "ERROR: Failed to init auth credentials: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information."
> 
> This is from [JAX Linux CPU](https://btx.cloud.google.com/invocations/6af16e78-eaa1-4cad-98f6-5199a7357d14/log) CI, right? It's just a CI infra error and is unrelated to this PR.
> 
> The [XLA Linux CPU](https://btx.cloud.google.com/invocations/de4aa5e1-4058-4370-a4fb-1c3b36c7fb6c/targets/tensorflow%2Fxla%2Flinux%2Fcpu%2Fbuild_cpu/log) CI has related errors though. Other targets should be able to build, with or without `--config=sycl`.

Thank you for your reply. I have added SYCL compilation constraints to the newly added compilation target.

2024-08-13 09:19 UTC, Zantares commented
There are some specific HW code in the original PR, and are simplified now. Please help to review it again, thanks!

2024-09-09 02:01 UTC, mayuyuace commented
@penpornk 
I have updated the code to fix conflicts. Please review this PR again, thank you.

2024-09-16 14:09 UTC, dimitar-asenov commented
@penpornk Could you please take a look at this PR?

2024-11-11 15:43 UTC, dimitar-asenov commented
@penpornk Could you please review this PR?

2025-01-13 09:35 UTC, penpornk requested changes
Posting my partial review from a while ago. Sorry for the delay!
Could you please also resolve conflicts?

We also have a stricter rules against `#ifdef`s, so I'd like to hold this PR back until I have restructured existing SYCL code to be as ifdef-free as possible.

2025-01-28 11:05 UTC, penpornk commented
Since there hasn't been a response in 2 weeks and I think this PR should wait until our infrastructure is ready, I'll close the PR for now. Please feel free to continue the discussion here or reopen the PR when it's ready.

2025-01-28 11:05 UTC, closed without merging