Heiner/gloo macos squash
openxla/xla pull request #16014
Opened 2024-08-13 02:28 UTC by heiner

This works for me(tm) on

```
$ uname -a
Darwin joeliel.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:37 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6031 arm64
```

I build the wheel via

```
python build/build.py --bazel_options=--override_repository=xla=~/src/xla/ --noenable_cuda
```

(in JAX, commit `833560deb1a94971c3f607a31b18d493b116e2d0`).

I then install the `jaxlib` wheel and update JAX via

```
uv pip install dist/jaxlib-0.4.32.dev20240812-cp310-cp310-macosx_11_0_arm64.whl --force-reinstall
uv pip install .
```

The following works:

```
$ python -c "import jax; print(jax.default_backend()); print(jax.devices()); print(len(jax.devices()))"
cpu
[CpuDevice(id=0)]
1
```

Likewise with this JAX wheel my use case for `jax_cpu_collectives_implementation:gloo` works on MacOS.

2024-08-13 02:31 UTC, heiner commented
However, when I try to run the test if fails for some seemingly unrelated reason:

```
$ ~/src/jax/build/bazel-6.5.0-darwin-arm64 run --test_output=errors --spawn_strategy=sandboxed //xla/pjrt/cpu:gloo_collectives_test
...
INFO: Running command line: external/bazel_tools/tools/test/test-setup.sh xla/pjrt/cpu/gloo_collectives_test
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //xla/pjrt/cpu:gloo_collectives_test
-----------------------------------------------------------------------------
dyld[43777]: symbol not found in flat namespace '__ZN9benchmark16PrintDefaultHelpEv'
external/bazel_tools/tools/test/test-setup.sh: line 333: 43777 Abort trap: 6           "${TEST_PATH}" "$@" 2>&1
     43778 Done                    | tee -a "${XML_OUTPUT_FILE}.log"
zsh: abort      ~/src/jax/build/bazel-6.5.0-darwin-arm64 run --test_output=errors
```

This seems something related to [google/benchmark](https://github.com/google/benchmark) but I'm not sure how to resolve it.

2024-08-13 02:32 UTC, heiner commented
Likewise, if I sync to current `main` the compilation fails due to an unrelated issue.

2024-08-13 02:55 UTC, heiner commented
Update: I fixed the test by adding `linkstatic=True`. It now runs like this:

```
$ ~/src/jax/build/bazel-6.5.0-darwin-arm64 run --test_output=errors --spawn_strategy=sandboxed //xla/pjrt/cpu:gloo_collectives_test
Executing tests from //xla/pjrt/cpu:gloo_collectives_test
-----------------------------------------------------------------------------
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from GlooCollectives
[ RUN      ] GlooCollectives.AllReduce
[       OK ] GlooCollectives.AllReduce (2 ms)
[----------] 1 test from GlooCollectives (2 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (2 ms total)
[  PASSED  ] 1 test.
external/bazel_tools/tools/test/test-setup.sh: line 353: 52357 Killed: 9               sleep 10
```

Not sure what the `Killed 9: sleep 10` is about.

2024-08-13 14:45 UTC, penpornk requested changes
Thank you for the fix and the investigation!

2024-08-13 14:45 UTC, penpornk commented on xla/pjrt/cpu/gloo_collectives_test.cc
> +#elif __APPLE__
Should this be `#elifdef`? Other places in XLA also check if it's defined.
```suggestion
#elifdef __APPLE__
```

2024-08-13 14:45 UTC, penpornk commented on xla/python/xla.cc
> +#elif __APPLE__
Same question here.
```suggestion
#elifdef __APPLE__
```

2024-08-14 08:24 UTC, penpornk approved these changes

2024-08-15 15:30 UTC, closed without merging