Unary Ops in FP8 Windowed Einsums
openxla/xla pull request #16893
Opened 2024-09-06 22:54 UTC by philipphack

Adds support for unary ops between dequantization and windowed einsum loop.

2024-09-10 10:32 UTC, cheshire commented
Could we somehow go back to the drawing board and figure out how to do this without excessive pattern matching?

2024-09-18 18:02 UTC, philipphack commented
@cheshire the windowed einsum handler effectively pattern matches and transforms windowed einsum loops created by the SPMD dot handler. The alternative would be the direct modification of the dot handler which is already relatively complex.

2024-09-18 22:28 UTC, reedwm requested changes

2024-09-18 22:28 UTC, reedwm commented on xla/service/gpu/transforms/windowed_einsum_handler.cc
> +//   inputs --> while loop {(unary) --> dequant --> collective-permute/dot/etc}.
The unary ops are stlil outside the while loop. So this line should be

```
//   inputs --> (unary) --> while loop {dequant --> collective-permute/dot/etc}.
```

2024-09-18 22:28 UTC, reedwm commented on xla/service/gpu/transforms/windowed_einsum_handler_test.cc
> +; CHECK:         [[WHILE0:%[^ ]+]] = (f8e4m3fn[2,512,24576]{2,1,0}, f8e4m3fn[24576,24576]{1,0}, f32[2,2048,24576]{2,1,0}, f32[2,2048,24576]{2,1,0}, u32[], /*index=5*/f32[], f32[]) while([[TUPLE0:%[^
Also check the RHS_RESHAPED is actually passed to the while-loop. If there were a bug that mistakenly passed the original RHS to the while-loop, no test would catch it right now.

Also I would add an end to end test.

2024-09-20 00:31 UTC, reedwm requested changes

2024-09-20 00:31 UTC, reedwm commented on xla/tests/collective_ops_e2e_test.cc
> +  ROOT custom-call = bf16[2,16,192]{2,1,0} custom-call(dot), custom_call_target="Sharding", sharding={devices=[1,1,4]<=[4]}
Just put the sharding annotation on the dot itself, by adding to the end: `, sharding={devices=[1,1,4]<=[4]}`

2024-09-20 00:31 UTC, reedwm commented on xla/tests/collective_ops_e2e_test.cc
> +  lhs = f8e4m3fn[2,16,48]{2,1,0} parameter(0), sharding={devices=[1,4,1]<=[4]}
Why have a two non-contracting dims? It's simply if there's just one.

2024-09-20 00:31 UTC, reedwm commented on xla/tests/collective_ops_e2e_test.cc
> +  lhs = f8e4m3fn[2,16,48]{2,1,0} parameter(0), sharding={devices=[1,4,1]<=[4]}
Why change this test?

2024-09-26 22:41 UTC, reedwm approved these changes

2024-09-27 07:32 UTC, closed without merging