[XLA:GPU] Fix default device mesh for auto sharding
openxla/xla pull request #16901
Opened 2024-09-07 05:14 UTC by i-Pear

When the user does not specify the number of GPUs for auto sharding, XLA defaults to using all available GPUs.

The current implementation uses the number of cores (SMs) on the GPU as the default shard count. For example, on an A100, the sharding algorithm will try to shard into 108 devices, which can be confusing for users.

This patch changes the shard count to the number of cards, which has been tested to work correctly on an 8-card A100 machine.

2024-09-13 16:34 UTC, bixia1 approved these changes

2024-09-16 14:20 UTC, dimitar-asenov approved these changes

2024-09-16 15:10 UTC, cheshire commented
Is it possible to test this?

2024-09-24 10:09 UTC, dimitar-asenov requested changes
Please add a test for the new change.

2024-11-22 00:38 UTC, closed without merging