Add NANOO FP8 support for collaborative communication unit tests
openxla/xla pull request #16938
Opened 2024-09-09 14:10 UTC by ScXfjiang

This PR adds support for NANOO FP8 data format in the collaborative communication unit tests.
- For the context on OCP FP8 and NANOO FP8, please refer to this comment:
https://github.com/google/flax/pull/3993#issue-2350000228
- This PR is based on the GEMM unit test introduced in the following PR:
https://github.com/openxla/xla/pull/9531

2024-09-13 04:41 UTC, wenchenvincent commented
@reedwm Could you take a look at this PR?

2024-09-13 18:14 UTC, reedwm requested changes

2024-09-17 10:24 UTC, ScXfjiang commented on xla/tests/collective_ops_e2e_test.cc
> +#if GOOGLE_CUDA
@reedwm Hi I have updated it!

2024-09-17 18:04 UTC, reedwm approved these changes

2024-09-19 09:43 UTC, ScXfjiang commented
Hi @reedwm, this PR hasn't been merged. Could you take a look at it? Many thanks!

2024-09-19 23:59 UTC, closed without merging