Add a few related optimization pass for fp8 gemm rerwriter.
openxla/xla pull request #16975
Opened 2024-09-10 00:43 UTC by elfiegg

This caused convergence issue for fp8 training, tested on GPT3 models:

Before:
```
NETWORK             BACKEND MATH SDPA XLA_EXTRAS      GPUs STEPS/SEC     LOSS
WALLSECS
GPT5B                   XLA  fp8   FA    8     1.064 11.019     1571
[PAX STATUS]: Starting training loop.
[PAX STATUS] step_i: 100, training loss: 11.015041
[PAX STATUS] step_i: 200, training loss: 11.016165
[PAX STATUS] step_i: 300, training loss: 11.016386
[PAX STATUS] step_i: 400, training loss: 11.014653
[PAX STATUS] step_i: 500, training loss: 11.014734
[PAX STATUS] step_i: 600, training loss: 11.01613
[PAX STATUS] step_i: 700, training loss: 11.009399
[PAX STATUS] step_i: 800, training loss: 11.017071
[PAX STATUS] step_i: 900, training loss: 11.014582
[PAX STATUS] step_i: 1000, training loss: 11.013434
[PAX STATUS] step_i: 1100, training loss: 11.021271
[PAX STATUS] step_i: 1200, training loss: 11.008364
[PAX STATUS] step_i: 1300, training loss: 11.0198145
[PAX STATUS] step_i: 1400, training loss: 11.01253
[PAX STATUS] step_i: 1500, training loss: 11.019016
```

After:
```
NETWORK             BACKEND MATH SDPA GPUs STEPS/SEC  LOSS WALLSECS
GPT5B                   XLA  fp8   FA    8     1.020 3.797     1647
[PAX STATUS]: Starting training loop.
[PAX STATUS] step_i: 100, training loss: 6.150083
[PAX STATUS] step_i: 200, training loss: 5.8871064
[PAX STATUS] step_i: 300, training loss: 5.4491887
[PAX STATUS] step_i: 400, training loss: 5.6384015
[PAX STATUS] step_i: 500, training loss: 5.273538
[PAX STATUS] step_i: 600, training loss: 5.2011905
[PAX STATUS] step_i: 700, training loss: 4.903013
[PAX STATUS] step_i: 800, training loss: 4.62972
[PAX STATUS] step_i: 900, training loss: 4.507727
[PAX STATUS] step_i: 1000, training loss: 4.625259
[PAX STATUS] step_i: 1100, training loss: 4.428066
[PAX STATUS] step_i: 1200, training loss: 4.252451
[PAX STATUS] step_i: 1300, training loss: 3.8448389
[PAX STATUS] step_i: 1400, training loss: 3.8578327
[PAX STATUS] step_i: 1500, training loss: 3.796958
```

2024-09-10 07:54 UTC, cheshire commented
Is it possible to add tests? Do we have an explanation why those passes are required for correctness?

2024-09-10 17:27 UTC, kaixih commented
Let me provide more context:

We are migrating from our original fake-quantization-like FP8 pattern to a new direct-quantization approach, where DQ scaling is applied as the epilogue of the dot operation. This change allows us to avoid concerns about other XLA optimizer passes breaking our patterns, as the dot can now directly handle FP8 inputs in direct-quantization and it will always be lowered to call fp8 gemm.

During the migration, @elfiegg found that wheh Triton GEMM falls back to the GEMM rewriter for cuBLAS, these three specific passes, i.e. LayoutNormalization, GpuAlgebraicSimplifier, and ScatterSimplifier, are necessary to ensure correctness. I think she is still investigating for the specific reason and looking for the unit test.

cc. @nouiz @sergachev @wenscarl @jprabhas

2024-09-10 17:32 UTC, cheshire commented
OK thanks for the context!

2024-09-11 22:47 UTC, elfiegg commented
Thanks Kaixi for bringing up everyone on the same page! Also sorry for the delay.

As mentioned, during debugging, we found that layout normalization is crucial for ensuring numerical correctness. We consistently reproduced the numerical issue when using different operand layout permutations with cuBLAS - operands such as `f8e4m3fn[4096,12288]{0,1} bitcast(f8e4m3fn[12288,4096]{1,0} %transpose)` vs. `f8e4m3fn[4096,12288]{0,1} transpose(f8e4m3fn[12288,4096]{0,1} %p0)` would cause numerical difference. This suggests that cublas runtime thunk is sensitive to logical layout changes, making LayoutNormalization necessary for the cublas GEMM rewriter.

I've also added a unit test to ensure numerical correctness in the pipeline, both with Triton fusion falling back to cuBLAS and without Triton fusion(the test will fail without the changes in this PR.)

2024-09-16 22:04 UTC, elfiegg commented
Removed a duplicate GpuAlgebraicSimplifier pass that is already in place in a later stage.  

Upon further investigation, it seems the cublas runtime thunk correctly processed the layout, and the final MatrixLayout of both operands and buffer assignments are identical for the cublasLt custom calls in both cases: f8e4m3fn[12288,4096]{1,0} and f8e4m3fn[4096,12288]{0,1}. Despite this, cublasLt produces different numerical results for the two calls. It's unclear what the root cause is. 

Since LayoutNormalization has been used in previous cublasLT FP8 GEMM calls without Triton fp8 gemm, I believe it's safe to proceed with adding this pass for now, pending further investigation.

2024-09-17 15:47 UTC, elfiegg commented
gentle ping @cheshire @reedwm

2024-09-17 17:41 UTC, elfiegg commented
Further investigation shows transpose seems broken for fp8 operands as following modules generate different numerics, for which I'll file another bug for tracking. 
```
  ENTRY main {
    %p0 = f8e5m2[12288,4096]{0,1} parameter(0)
    %b = f8e5m2[4096,12288]{1,0} bitcast(%p0)
    ROOT %transpose = f8e5m2[12288,4096]{1,0} transpose(%b), dimensions={1,0}
  }
```
```
ENTRY main {
    %p0 = f8e5m2[12288,4096]{0,1} parameter(0)
    %transpose = f8e5m2[4096,12288]{0,1} transpose(%p0), dimensions={1,0}
    ROOT %bitcast = f8e5m2[12288,4096]{1,0} bitcast(%transpose)
  }
```

2024-09-17 22:36 UTC, reedwm requested changes
I'm not sure why this is necessary. It seems the core issue is that certain layouts have incorrect numerics. That said, I'm ok taking this for now if it does fix the layout issue, but in the long term it's better to directly ensure different layouts still have correct numerics.

Does LayoutNormalization even affect a cublas gemm custom call? I see we pass `NormalizeLayoutForGpuCustomCalls`, but that only affects convolutions, not gemms.

2024-09-17 22:48 UTC, kaixih commented
> Does LayoutNormalization even affect a cublas gemm custom call? 

@elfie just filed [an issue](https://github.com/openxla/xla/issues/17276) to further narrow down the issue, hopefully. Here's the current understanding:

We’ve learned that the GEMM rewriter inserts a transpose for one operand as follows:
```
(x, y){0,1} -> transpose -> (y, x){0,1} -> gemm
```
However, directly running this results in incorrect outputs.

Upon investigation, we found that the **layout normalization pass** inserts a bitcast to ensure the following pattern works:
```
(x, y){0,1} -> bitcast -> (y, x){1,0} -> transpose -> (x, y){1,0} -> bitcast -> (y, x){0,1} -> gemm
```

This modification produces the correct results. Given this, we are curious if there is a usage restriction that the transpose must operate over a `{1,0}` layout for it to work properly. This might suggest that the transpose function or the underlying operation requires this specific layout to avoid issues.

2024-09-17 23:03 UTC, reedwm commented
That makes sense. Thanks @elfiegg for the steps to reproduce the issue! CC @mooskagh

2024-09-17 23:22 UTC, elfiegg commented on xla/service/gpu/gpu_compiler_test.cc
> +  config.set_num_partitions(1);
Done.

2024-09-17 23:22 UTC, elfiegg commented on xla/service/gpu/gpu_compiler_test.cc
> +  triton_enabled_debug_options.set_xla_gpu_enable_dynamic_slice_fusion(false);
No shame in copy-pasting from the other test ;:^^)

2024-09-17 23:22 UTC, elfiegg commented on xla/service/gpu/gpu_compiler_test.cc
> +                        "gpu_compiler_test_autotune_db.textproto");
Ah let me clarify - the test is comparing triton enabled but falling back to cublasLT vs. triton disabled paths. Regarding that do you have any suggestion / concern? 
Renamed the test to be clearer.

2024-09-17 23:30 UTC, elfiegg commented
Thanks again Kaixi for helping bridge the communication gaps.

> Does LayoutNormalization even affect a cublas gemm custom call? I see we pass NormalizeLayoutForGpuCustomCalls, but that only affects convolutions, not gemms.

Regarding this, I had the same confusion. It seems that the pipeline may still use legacy naming for historical reasons, which we should consider updating. However, as mentioned, the pass is indeed normalizing non-default layouts of transform instructions to the default layout. We have also observed numerical differences in the execution results after this transformation.

2024-09-17 23:38 UTC, reedwm approved these changes

2024-09-17 23:38 UTC, reedwm commented on xla/service/gpu/gpu_compiler_test.cc
> +                        "gpu_compiler_test_autotune_db.textproto");
That makes sense, and the test name clarifies things. I forgot that GemmRewriter is called twice: Once to handle gemms that the Triton rewriter didn't handle, and again to handle formerly-Triton fusions that the autotuner decided to use cublas for. So good to test the two cases are equivalent numerically.

2024-09-18 18:44 UTC, reedwm approved these changes

2024-09-18 20:10 UTC, reedwm requested changes
I'm seeing the added test fail internally:

```
[ RUN      ] GpuCompilerTest.CublasF8NumericallySameWithTritonFallbackAndWithoutTriton
[third_party/tensorflow/compiler/xla/service/gpu/gpu_compiler_test.cc:509](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/xla/service/gpu/gpu_compiler_test.cc?l=509&ws=tap-presubmit-rerun-server/42622556&snapshot=2): Failure
Value of: (AutotunerUtil::LoadAutotuneResultsFromFile(path))
Expected: is OK
  Actual: INTERNAL: Duplicate autotuning result for <key model='CUDA: 8.0, Cores: 108, GPU clock: 1.41 GHz, Memory bandwidth: 1555 GB/s, L2 cache: 40 MB', hlo='(bf16[128,1024,1024]{2,1,0}, s8[4194304]{0}) custom-call(bf16[128,1024,1024]{2,1,0}, bf16[128,1024,1024]{2,1,0}), custom_call_target="__cublas$gemm", backend_config={"force_earliest_schedule":false,"gemm_backend_config":{"alpha_imag":0,"alpha_real":1,"beta":0,"damax_output":false,"dot_dimension_numbers":{"lhs_batch_dimensions":["0"],"lhs_contracting_dimensions":["2"],"rhs_batch_dimensions":["0"],"rhs_contracting_dimensions":["1"]},"epilogue":"DEFAULT","grad_x":false,"grad_y":false,"lhs_stride":"1048576","precision_config":{"algorithm":"ALG_UNSET","operand_precision":["DEFAULT","DEFAULT"]},"rhs_stride":"1048576"},"operation_queue_id":"0","wait_on_operation_queues":[]}'>
=== Source Location Trace: === 
[third_party/tensorflow/compiler/xla/service/gpu/autotuning/autotuner_util.cc:283](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/xla/service/gpu/autotuning/autotuner_util.cc?l=283&ws=tap-presubmit-rerun-server/42622556&snapshot=2)
[third_party/tensorflow/compiler/xla/service/gpu/autotuning/autotuner_util.cc:510](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/xla/service/gpu/autotuning/autotuner_util.cc?l=510&ws=tap-presubmit-rerun-server/42622556&snapshot=2)
[third_party/tensorflow/compiler/xla/service/gpu/autotuning/autotuner_util.cc:567](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/xla/service/gpu/autotuning/autotuner_util.cc?l=567&ws=tap-presubmit-rerun-server/42622556&snapshot=2)
```

Are you seeing this error? My guess is that this is occuring since you call `AutotunerUtil::LoadAutotuneResultsFromFile` in two tests now, which results in the duplicate autotuning results. If I'm correct, than I think this can be fixed by calling `AutotunerUtil::LoadAutotuneResultsFromFile` only once, by calling it in [`SetUpTestSuite`](https://google.github.io/googletest/advanced.html#sharing-resources-between-tests-in-the-same-test-suite) instead of the tests themselves.

2024-09-18 23:58 UTC, elfiegg commented
Added test suit for fixing it. Previously I used a test filter so I didn't come across this issue. I noticed there is Hopper GPU variation in terms of memory bandwidth and L2 cache size, which makes the test a bit of fragile. For one of my tested chips it was `CUDA: 9.0, Cores: 132, GPU clock: 1.98 GHz, Memory bandwidth: 2447 GB/s, L2 cache: 60 MB` while Google's chip seems to be `CUDA: 9.0, Cores: 132, GPU clock: 1.98 GHz, Memory bandwidth: 3352 GB/s, L2 cache: 50 MB`. I'm changing all autotune results to be consistent with Google's settings and let me know if the internal pipeline passes.

2024-09-19 00:32 UTC, reedwm approved these changes

2024-10-09 09:06 UTC, derdrdirk commented
"This branch has conflicts that must be resolved"

Could you sync to head? IIUC the PR cannot be imported by copybara due to a conflict with head.

2024-10-10 19:11 UTC, reedwm approved these changes

2024-10-12 09:54 UTC, closed without merging

2024-10-15 04:26 UTC, derdrdirk commented
Currently investigating if I can provide a fix and roll forward.