[XLA:CPU][oneDNN] Move addend shape checks to the rewriter and alias result to addend when feasible
openxla/xla pull request #17637
Opened 2024-09-26 06:51 UTC by akhilgoe

This PR:

1. Moves the addend shape check to the rewriter so that the code to append oneDNN post-ops can be shared between matmul and convolution kernels.
2. Adds a new oneDNN post-op type that will perform in-place addition whenever there is no broadcast overhead.
3. Pads the MemrefInfoPod emitted on stack so that it aligns with the system cacheline.
4. Adds tests to verify the functionality.

2024-10-29 18:22 UTC, penpornk requested changes
Thank you for the PR and sorry for the delay!

2024-10-29 18:25 UTC, akhilgoe commented on xla/service/cpu/onednn_memory_util.cc
Thanks @penpornk, yes you are right. I felt the same way and created this PR https://github.com/openxla/xla/pull/18688
I will rebase this PR to remove these changes and address your comments. Thanks!

2024-11-22 05:28 UTC, akhilgoe commented
Thanks @penpornk for the review! I have added a commit to address your comments and created separate PRs for isolated changes.

2024-11-22 05:28 UTC, akhilgoe commented on xla/service/cpu/onednn_contraction_rewriter.cc
> +    }
Done

2024-11-22 05:28 UTC, akhilgoe commented on xla/service/cpu/onednn_config.proto
> +    SUM = 11;
Done

2024-11-22 05:28 UTC, akhilgoe commented on xla/service/cpu/onednn_matmul.cc
> +        break;
Done

2025-01-17 00:42 UTC, akhilgoe commented
@penpornk A gentle reminder!

2025-01-28 11:00 UTC, penpornk requested changes
Sorry for the delay!

2025-02-06 17:00 UTC, akhilgoe commented on xla/service/cpu/onednn_convolution.cc
> +    if (conv_config.fusions().ops(i) == OneDnnFusionConfig::SUM) {
We don't need a memref for the addend because oneDNN does not take operand inputs for SUM fusions. The buffers are aliased and oneDNN would perform in-place accumulation.

2025-02-06 17:01 UTC, akhilgoe commented on xla/service/cpu/onednn_matmul.cc
> +    if (matmul_config.fusions().ops(i) == OneDnnFusionConfig::SUM) {
Done

2025-02-06 17:02 UTC, akhilgoe commented
Hi @penpornk! Apologies for the delay. I created a commit to address your comments. Please take a look, thanks!

2025-04-08 14:44 UTC, penpornk approved these changes
Thank you for the changes and sorry for the delay!

2025-04-08 16:13 UTC, closed without merging