Pass Ordering Test for GPU Compiler
openxla/xla pull request #18065
Opened 2024-10-08 22:55 UTC by philipphack

Adds a class for testing the order of passes in the GPU compiler. The names of the passes expected to run first and last can be described by regular expressions.

Also adds a test for verifying the order of the collective quantizer and collective pipeliner passes.

2024-10-09 00:29 UTC, reedwm requested changes

2024-10-09 00:29 UTC, reedwm commented on xla/service/gpu/gpu_compiler_test.cc
> +    int first_last_run = -1;
Change this to `latest_run_of_first`. Or maybe `first_latest_run`. And similarly for `last_first_run`.

2024-10-09 12:54 UTC, bchetioui requested changes

2024-10-09 12:54 UTC, bchetioui commented on xla/service/gpu/gpu_compiler_test.cc
> +  void SetModuleConfig(const HloModuleConfig& config) {
Do we need this additional indirection? (The name is also not intuitive for what it does.)

It seems like we could get away just fine with `SetDebugOptions`, and have a `private` "`CompileModule`" that would generate the module if it doesn't exist, and is called in `VerifyPassOrder`.

2024-10-09 12:54 UTC, bchetioui commented on xla/service/gpu/gpu_compiler_test.cc
> +                       absl::string_view last_regex) {
I'm having a bit of a hard time following the terminology between `first_latest` and `last_earliest`.

Could we stick to the previous terminology? (I.e. `first` -> `before`, `earliest` -> `first`, ...)
We could even make it `before_pass_regex` to enhance clarity further.

2024-10-10 07:40 UTC, bchetioui approved these changes
Thanks for the enhancement!

2024-10-10 16:26 UTC, closed without merging