Shape inference: check that atan2 inputs are float or complex.
openxla/xla pull request #18435
Opened 2024-10-17 12:51 UTC by sergachev

2024-10-18 17:19 UTC, bchetioui approved these changes

2024-10-19 20:11 UTC, sergachev commented
Added a fix for triton_support_test.

2024-10-21 06:38 UTC, bchetioui requested changes

2024-10-21 06:38 UTC, bchetioui commented on xla/service/gpu/fusions/triton/triton_support_test.cc
> +  if (opcode == HloOpcode::kAtan2 &&
Same comment as in the `cbrt` PR, this check should be done in `DoesOpSupportType` (and same for the above filter)!

2024-10-22 11:45 UTC, closed without merging