[XLA:CPU][oneDNN] Handle oneDNN scalar
openxla/xla pull request #19066
Opened 2024-11-05 17:59 UTC by mahmoud-abuzaina

This PR makes sure oneDNN handles the scalar properly.

2025-01-06 10:10 UTC, penpornk requested changes
Thank you for the PR and sorry for the delay!

2025-01-06 10:10 UTC, penpornk commented on xla/service/cpu/onednn_memory_util.cc
> +    }
Could you please refactor this code to a utility function and call it from both `GetAllocaAndEmitMemrefInfo` and `ShapeToMemDesc`?

2025-01-07 23:53 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_memory_util.cc
> +    }
Done.

2025-01-07 23:54 UTC, mahmoud-abuzaina commented
Thank you for reviewing the PR! I have made the requested change.

2025-01-08 12:55 UTC, penpornk requested changes

2025-01-08 12:55 UTC, penpornk commented on xla/service/cpu/onednn_memory_util.cc
> +                    std::vector<int64_t>& strides) {
Nit: We prefer returning the output over having it as a parameter. Please change?

2025-01-08 16:42 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_memory_util.cc
> +                    std::vector<int64_t>& strides) {
Done. I also renamed the function name to GetDimsStrides. Please let me know if that looks ok. Thanks!

2025-01-08 17:39 UTC, penpornk requested changes

2025-01-08 17:39 UTC, penpornk commented on xla/service/cpu/onednn_memory_util.cc
> +  auto dims_strides = GetDimsStrides(shape);
One last nit please:
We can unpack the pair to two separate variables to improve readability. See below for example:
https://github.com/openxla/xla/blob/cbcde508791510b6bd0593d3ac198378eb95e478/xla/backends/cpu/runtime/sort_thunk.cc#L161

2025-01-08 18:08 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_memory_util.cc
> +  auto dims_strides = GetDimsStrides(shape);
Sure. I made the change.

2025-01-08 20:09 UTC, penpornk approved these changes
Thank you again for the PR!

2025-01-09 19:13 UTC, sdasgup3 commented
The approvals looks stale and may that is way workflows are waiting.  
@penpornk Can you please approve this again?

2025-01-10 10:13 UTC, penpornk approved these changes

2025-01-11 02:18 UTC, closed without merging