[XLA:CPU][oneDNN] Add post-ops for oneDNN Convolutions
openxla/xla pull request #19099
Opened 2024-11-06 09:20 UTC by akhilgoe

This PR adds support for multiple post-ops for oneDNN Convolution and adds tests to verify functionality. New Post-ops supported:

1. Relu
2. Tanh
3. Gelu (Approx.)
4. Gelu (Exact)
5. Relu6
6. Sigmoid
7. Elu
8. Elementwise scalar product

2024-11-07 19:04 UTC, akhilgoe reviewed
Hi @penpornk, this PR has minor overlap in some header files with https://github.com/openxla/xla/pull/19099. I have marked those areas for your convenience. Thanks!

2024-11-07 19:04 UTC, akhilgoe commented on xla/service/cpu/onednn_contraction_rewriter.cc
> +auto GetOneDnnContractionVariant(
Overlap with https://github.com/openxla/xla/pull/19099

2024-11-07 19:04 UTC, akhilgoe commented on xla/service/cpu/onednn_contraction_rewriter.h
> +using OneDnnContractionVariant =
Overlap with https://github.com/openxla/xla/pull/19099

2024-11-07 19:04 UTC, akhilgoe commented on xla/service/cpu/onednn_convolution.h
> +  static const BackendConfigOneofCase kConfigVal = kOnednnConvConfig;
Overlap with https://github.com/openxla/xla/pull/19099

2024-11-07 19:04 UTC, akhilgoe commented on xla/service/cpu/onednn_matmul.h
> +  static const BackendConfigOneofCase kConfigVal = kOnednnMatmulConfig;
Overlap with https://github.com/openxla/xla/pull/19099

2024-11-07 19:04 UTC, akhilgoe commented on xla/service/cpu/onednn_util.h
> +template <BackendConfigOneofCase config, typename TransformationType = void>
Overlap with https://github.com/openxla/xla/pull/19099

2024-12-05 19:02 UTC, penpornk requested changes
@akhilgoe Sorry for the delay! https://github.com/openxla/xla/pull/18616 has been merged. Could you please help resolve the conflicts?

2024-12-05 21:37 UTC, akhilgoe commented
Thanks @penpornk, I have resolved the conflicts.

2024-12-11 21:16 UTC, penpornk approved these changes
Thank you again for the PR!

2024-12-12 12:09 UTC, closed without merging