Add support for fusion operations in GetLoopInductionVariableIndex
openxla/xla pull request #19160
Opened 2024-11-07 18:55 UTC by shraiysh

After optimizations, while loop analysis was unable to handle the fused operations, primarily for GetLoopInductionVariableIndex and ComputeWhileLoopTripCount. This patch handles only GetloopInductionVariableIdx.

If the GetGTEOperandIndex function fails to find a precise GTE operand, we try to deduce the unique dependence by using the HloExtractor.

2024-11-07 18:57 UTC, shraiysh commented
This is another attempt at #18765. There is a fast path now, that relies on exact pattern matching. If the pattern matching is successful, then the slower version of extraction is not used. This should help with the timeouts.

2024-11-08 06:50 UTC, akuegel requested changes
Maybe the fast path would already help for those timeouts we have seen, but I think you are still not guarding about a while loop conditional that is conceptually like this:

Shape s32[10000000]
while loop body does divide by 2
while loop condition does a reduction and checks whether the sum of values in the tensor is 0.
This will be a quite expensive conditional computation that we probably don't want to evaluate during while loop analysis. My suggested fix is to never allow calling the Evaluator if there is any non-scalar shape involved. Can you please add a guard like that?

2024-11-08 07:43 UTC, shraiysh commented
> Maybe the fast path would already help for those timeouts we have seen, but I think you are still not guarding about a while loop conditional that is conceptually like this:
> 
> Shape s32[10000000] while loop body does divide by 2 while loop condition does a reduction and checks whether the sum of values in the tensor is 0. This will be a quite expensive conditional computation that we probably don't want to evaluate during while loop analysis. My suggested fix is to never allow calling the Evaluator if there is any non-scalar shape involved. Can you please add a guard like that?

I am not making any changes to the evaluation workflow for the computation of while loop -- that is done in the while loop trip count functions, that I have not edited (except making them stricter with the pattern they were already expecting). This patch does not actually execute the HLO instructions. This only deals with extracting the HLO and deciding whether the only dependence is on the induction variable or not. I thought I will do the changes for evaluation in a separate patch so that this lands in a clean fashion.

2024-11-08 12:55 UTC, akuegel commented
> I am not making any changes to the evaluation workflow for the computation of while loop -- that is done in the while loop trip count functions, that I have not edited (except making them stricter with the pattern they were already expecting). This patch does not actually execute the HLO instructions. This only deals with extracting the HLO and deciding whether the only dependence is on the induction variable or not. I thought I will do the changes for evaluation in a separate patch so that this lands in a clean fashion.

I think your change makes it much more likely that we will evaluate the condition computation. It is quite likely that we didn't need any guards so far because not supporting fusion instructions already acted as a guard. I agree that maybe it would be better to add such a guard in a separate PR, but that one would have to land first before we can land this one.

2024-11-08 17:42 UTC, shraiysh commented
> I think your change makes it much more likely that we will evaluate the condition computation. It is quite likely that we didn't need any guards so far because not supporting fusion instructions already acted as a guard. I agree that maybe it would be better to add such a guard in a separate PR, but that one would have to land first before we can land this one.

Added it in #19194.

2024-11-08 17:45 UTC, akuegel commented
> > I think your change makes it much more likely that we will evaluate the condition computation. It is quite likely that we didn't need any guards so far because not supporting fusion instructions already acted as a guard. I agree that maybe it would be better to add such a guard in a separate PR, but that one would have to land first before we can land this one.
> 
> Added it in #19194.

Thank you, I will review it on Monday, today it is already end of work time for me.

2024-11-12 20:22 UTC, fhoushmand approved these changes

2024-11-13 07:55 UTC, akuegel commented
I verified that this PR now does not trigger the timeouts anymore. Also, I found out why we were hitting the timeouts before. HloExtractor has a performance bug in FinishVisit() method, I am fixing that now and that alone would have already fixed the issue. But still good that we have the other guard, too.

2024-11-13 18:36 UTC, shraiysh commented
> I verified that this PR now does not trigger the timeouts anymore. Also, I found out why we were hitting the timeouts before. HloExtractor has a performance bug in FinishVisit() method, I am fixing that now and that alone would have already fixed the issue. But still good that we have the other guard, too.

Oh, that's good to know. I suspected that there could be issues with HloExtractor. Thanks for looking into it :)

2024-11-14 06:27 UTC, akuegel commented
> Do we know why this was reverted @akuegel @fhoushmand ?

This time it was not due to timeouts, but due to a verifier error. It points to a shape mismatch, so probably a missing check somewhere. I will try to extract a reproducer.

2024-11-14 07:26 UTC, akuegel commented
> > Do we know why this was reverted @akuegel @fhoushmand ?
> 
> This time it was not due to timeouts, but due to a verifier error. It points to a shape mismatch, so probably a missing check somewhere. I will try to extract a reproducer.

So far I narrowed it down to the WhileLoopFusibleSinking pass. When I disable that pass, the problem goes away, so I guess this pass has some assumption that only holds for trivial pattern matching. Will now look at the code of the pass if I see something.

2024-11-14 11:11 UTC, akuegel commented
Rolled forward in https://github.com/openxla/xla/commit/f25e9a00b48a083ede7f2075f16ca50aebf280a0

2024-11-14 11:11 UTC, closed without merging