Cleanup handling of 3 fields of ExecutableBuildOptions.
openxla/xla pull request #19577
Opened 2024-11-21 00:03 UTC by sergachev

2024-11-21 00:25 UTC, sergachev commented
cc @jaro-sevcik

2024-11-21 10:42 UTC, akuegel reviewed
Is it possible to write a test?
As far as I understand, we now allow to serialize the process index and the process count to a proto, and deserialize from proto. I think it is testable.

2024-11-21 10:48 UTC, sergachev commented
Sure, I can add a test for this. The change is motivated by https://github.com/openxla/xla/pull/19237#issuecomment-2482333092.

2024-11-21 12:30 UTC, akuegel reviewed
Thanks. Just one tiny nit.

2024-11-21 12:30 UTC, akuegel commented on xla/client/executable_build_options_test.cc
> +std::unique_ptr<tsl::protobuf::Message> ProcessNewEnv(
missing `#include <memory>`

2024-11-21 12:34 UTC, sergachev commented on xla/client/executable_build_options_test.cc
> +std::unique_ptr<tsl::protobuf::Message> ProcessNewEnv(
done

2024-11-21 12:37 UTC, akuegel approved these changes

2024-11-21 16:07 UTC, dimitar-asenov requested changes

2024-11-22 10:33 UTC, sergachev commented on xla/client/executable_build_options.cc
> +  if (key_value_store() != nullptr) {
done

2024-11-22 10:35 UTC, akuegel approved these changes

2024-11-22 12:36 UTC, closed without merging