Add support for emitting a kCall from an async instruction
openxla/xla pull request #20155
Opened 2024-12-04 21:45 UTC by chaserileyroberts

This is the last PR needed to enable the explicit stream annotation feature.

This PR enables the IR emitter for kCall subroutines that are wrapped in async-{start,done} pairs. For start, the instructions in the kCall are converted to a `SequentialThunk`. This thunk and the inner thunks are then annotated with their respective `execution_stream_ids`. (These ids come from #19699)

2024-12-04 22:04 UTC, chaserileyroberts commented
I'm not sure what is the best way to test this. Perhaps I should just wait for #19462 and #19699 to be merged first?

2024-12-10 18:53 UTC, bchetioui requested changes
I think adding an e2e test sounds good to me, but I'd also suggest adding a test that this generates a thunk with the correct stream information.

What do you think?

2024-12-10 19:34 UTC, bchetioui commented
I'm not sure there's a dedicated space atm. How about just creating a `ir_emitter_unnested_test.cc` file?

2024-12-12 00:12 UTC, chaserileyroberts commented
> How about just creating a ir_emitter_unnested_test.cc file?

Works for me.

2025-01-13 08:58 UTC, bchetioui commented
Hi @chaserileyroberts! What's the status of this change---do you still plan to land it?

2025-01-13 17:06 UTC, chaserileyroberts commented
Yes, I was waiting for #19462 and #19699 to land first to so I could make the e2e tests, which thankfully today they both just got merged. I'll update this asap.

2025-01-14 20:42 UTC, mjsML commented
Can we request the prioritization of this PR to land please and thank you.

2025-01-14 20:56 UTC, bchetioui commented
> Can we request the prioritization of this PR to land please and thank you.

If I read correctly, this is not yet updated/ready for review, right?

2025-01-22 09:47 UTC, bchetioui requested changes
Thanks! A few comments mostly around readability of the change & tests, but the core seems fine :)

2025-01-22 09:47 UTC, bchetioui commented on xla/service/gpu/gpu_compiler_test.cc
> +%f.3 (Arg_0.4: f32[32,32], Arg_1.5: f32[32,32]) -> f32[32,32] {
Could we prettify this test to enhance readability?

Here are a few recommendations that I think we should generally respect:

1. give meaningful names to variables as we would in real code;
2. omit leading `%`s which are not necessary and don't improve readability;
3. omit computation signatures;
4. remove all metadata, and only keep the strict minimum information necessary in backend configs (Is all of what is here necessary for the test to pass using `__cublas$gemm`? If so maybe we can use a custom call with less parameters to enhance readability.

2025-01-22 09:47 UTC, bchetioui commented on xla/service/gpu/gpu_compiler_test.cc
> +  auto module = ParseAndReturnVerifiedModule(hlo_text).value();
```
TF_ASSERT_OK_AND_ASSIGN(auto module, ...);
```

is the more usual pattern :)

2025-01-22 09:47 UTC, bchetioui commented on xla/service/gpu/ir_emitter_unnested.cc
> +          DCHECK_EQ(wrapped->called_computations().size(), 1);
Unless the check is expensive, XLA prefers using `CHECK`s to `DCHECK`s! Please change it!

2025-01-22 09:47 UTC, bchetioui commented on xla/service/gpu/ir_emitter_unnested.cc
> +          const ExecutionStreamAssignment& stream_assignment =
This is pretty long, let's use a helper function (`return Emit...`) instead to decrease this function's cognitive complexity!

2025-01-24 08:24 UTC, jreiffers commented on xla/service/gpu/ir_emitter_unnested.cc
> +          DCHECK_EQ(wrapped->called_computations().size(), 1);
Why not TF_RET_CHECK?

2025-01-24 08:27 UTC, chaserileyroberts commented on xla/service/gpu/gpu_compiler_test.cc
> +%f.3 (Arg_0.4: f32[32,32], Arg_1.5: f32[32,32]) -> f32[32,32] {
I did my best to reduce the complexity of the HLO. The gemm still has a lot of metadata, but I tried to keep it to the strict necessities for the test to pass.

2025-01-24 08:27 UTC, chaserileyroberts commented on xla/service/gpu/gpu_compiler_test.cc
> +  auto module = ParseAndReturnVerifiedModule(hlo_text).value();
Fixed.

2025-01-24 08:27 UTC, chaserileyroberts commented on xla/service/gpu/ir_emitter_unnested.cc
> +          DCHECK_EQ(wrapped->called_computations().size(), 1);
Fixed.

2025-01-24 08:28 UTC, chaserileyroberts commented on xla/service/gpu/ir_emitter_unnested.cc
> +          const ExecutionStreamAssignment& stream_assignment =
I broke out the code into `EmitAsyncComputation`.

2025-01-24 08:34 UTC, chaserileyroberts commented
@bchetioui I believe I've addressed your comments.

2025-01-24 08:56 UTC, jreiffers commented on xla/service/gpu/gpu_compiler_test.cc
> +  EXPECT_EQ(gpu_exec->GetThunk().thunks().size(), 3);
Nit: `EXPECT_EQ(gpu_exec->GetThunk().thunks(), testing::SizeIs(3))` is typically preferred.

Alternatively, I think this test could be improved with a matcher, something like this:

```
MATCHER_P(ThunkKindIs, kind, "") {
  return ExplainMatchResult(Eq(kind), arg->kind(), result_listener);
}

EXPECT_THAT(gpu_exec->GetThunk().thunks(), ElementsAre(ThunkTypeIs(...), ThunkTypeIs(...), ThunkTypeIs(...)));
```

IMO the latter is more readable and has the advantage of testing all the thunk types, not just the middle one.

@bchetioui opinions?

2025-01-24 08:56 UTC, jreiffers commented on xla/service/gpu/gpu_compiler_test.cc
> +  EXPECT_EQ(gpu_exec->GetThunk().thunks()[1]->kind(), Thunk::kSequential);
This should be an assert, or the static cast down there should be a dynamic cast with a guard. Or both :-).

2025-01-24 08:56 UTC, jreiffers commented on xla/service/gpu/gpu_compiler_test.cc
> +      static_cast<SequentialThunk*>(gpu_exec->GetThunk().thunks()[1].get());
We'll want another SizeIs check here.

2025-01-24 08:56 UTC, jreiffers commented on xla/service/gpu/ir_emitter_unnested.cc
> +          for (auto& thunk : thunk_sequence->thunks()) {
Can you leave a comment explaining why we need to set this on both the sequential thunk and its contents? Just an API quirk?

2025-01-24 08:56 UTC, jreiffers commented on xla/service/gpu/gpu_compiler_test.cc
> +%f.3 (Arg_0.4: f32[32,32], Arg_1.5: f32[32,32]) -> f32[32,32] {
How about something along the lines of this?

```
HloModule composite

async_call {
  p0 = f32[32,32] parameter(0)
  p1 = f32[32,32] parameter(1)
  gemm = (f32[32,32], s8[8192]) custom-call(p0, p1), custom_call_target="__cublas$gemm",
    backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],
      "gemm_backend_config":{"alpha_real":1,"alpha_imag":0,"beta":0,
      "dot_dimension_numbers":
        {"lhs_contracting_dimensions":["1"],"rhs_contracting_dimensions":["0"]},
      "precision_config":{"operand_precision":["DEFAULT","DEFAULT"]},
      "lhs_stride":"1024","rhs_stride":"1024"}}
  ROOT get-tuple-element = f32[32,32] get-tuple-element(gemm), index=0
}, execution_thread="explicit"

ENTRY main {
  p0 = f32[32,32] parameter(0)
  p1 = f32[32,32] parameter(1)
  call-start = ((f32[32,32], f32[32,32]), f32[32,32]) call-start(p0, p1),
    async_execution_thread="explicit", to_apply=async_call, 
    frontend_attributes={_xla_stream_annotation="1"}
  ROOT call-done = f32[32,32]{1,0} call-done(call-start),
    frontend_attributes={_xla_stream_annotation="1"},
    backend_config={"operation_queue_id":"0"}
}
```

2025-01-24 09:00 UTC, bchetioui commented on xla/service/gpu/gpu_compiler_test.cc
> +  EXPECT_EQ(gpu_exec->GetThunk().thunks().size(), 3);
Good catch. I'd also be happiest with the matcher!

2025-01-24 19:28 UTC, chaserileyroberts commented on xla/service/gpu/gpu_compiler_test.cc
> +  EXPECT_EQ(gpu_exec->GetThunk().thunks().size(), 3);
Added

2025-01-24 19:29 UTC, chaserileyroberts commented on xla/service/gpu/gpu_compiler_test.cc
> +  EXPECT_EQ(gpu_exec->GetThunk().thunks()[1]->kind(), Thunk::kSequential);
I changed this to use the matcher pattern you suggested instead.

2025-01-24 19:30 UTC, chaserileyroberts commented on xla/service/gpu/gpu_compiler_test.cc
> +      static_cast<SequentialThunk*>(gpu_exec->GetThunk().thunks()[1].get());
Added.

2025-01-27 08:04 UTC, jreiffers approved these changes
Thanks!

2025-01-27 08:10 UTC, bchetioui approved these changes
Thanks @chaserileyroberts for thoughtfully addressing comments, and thanks @jreiffers for the review assist!

2025-01-27 09:35 UTC, closed without merging