Add runtime support for host calculation of offsets in ds fusion
openxla/xla pull request #20332
Opened 2024-12-09 22:09 UTC by shraiysh

This patch adds the support for calculating offset on the host at runtime when the offset depends on the loop induction variable. This is done by extracting the offset computation, the induction variable initialization and the induction variable update as independent computations and they are evaluated on the host at runtime. This avoids device-to-host copy for this fusion in these cases.

2025-01-10 11:19 UTC, bchetioui requested changes

2025-01-10 11:19 UTC, bchetioui commented on xla/service/gpu/fusions/dynamic_slice_fusion_test.cc
> +  HloModule** offset1 = std::get_if<HloModule*>(&output_offsets[0]);
`offset1` seems a bit confusing since you check `output_offsets[1]` below. Maybe assign this to a variable `offset_0` instead? (Underscore added for general consistency.)

2025-01-10 11:19 UTC, bchetioui commented on xla/service/gpu/fusions/dynamic_slice_fusion_test.cc
> +  ErrorSpec error{1e-5, 1e-5};
This is working with integers, why is the error spec not `0`?

2025-01-10 11:19 UTC, bchetioui commented on xla/service/gpu/fusions/dynamic_slice_fusion_test.cc
> +      /*run_hlo_passes=*/false, /*use_threads=*/true, error);
How can we check that the offset computations are actually happening on the host and not on the device?

2025-01-10 11:19 UTC, bchetioui commented on xla/service/gpu/fusions/custom.cc
> +  std::vector<std::unique_ptr<HloModule>> temp_modules;
See other comments regarding this variable name.

2025-01-10 11:19 UTC, bchetioui commented on xla/service/gpu/fusions/custom.cc
> +  std::vector<std::unique_ptr<HloModule>> temp_modules;
See other comments regarding this variable name.

2025-01-10 11:19 UTC, bchetioui commented on xla/service/gpu/fusions/custom.cc
> +  std::vector<std::unique_ptr<HloModule>> temp_modules;
See other comments regarding this variable name.

2025-01-10 11:19 UTC, bchetioui commented on xla/service/gpu/runtime/dynamic_slice_thunk.cc
> +                                          std::unique_ptr<Literal>>
Why can't we just make `DynamicSliceThunk` hold a pointer to a literal, as opposed to having a `static thread_local` map?

This will outlive the existence of a thunk, and could potentially lead to some kind of UAF if a `DynamicSliceThunk` gets freed and another gets allocated in the same place.

Am I missing something?

2025-01-10 11:19 UTC, bchetioui commented on xla/service/gpu/runtime/dynamic_slice_thunk.cc
> +    std::vector<std::unique_ptr<HloModule>> temp_modules,
See other comments regarding this variable name.

2025-01-10 11:19 UTC, bchetioui commented on xla/service/gpu/runtime/dynamic_slice_thunk.cc
> +std::unique_ptr<Literal>& Indvar(DynamicSliceThunk* thunk) {
This deserves documentation.

2025-01-10 11:19 UTC, bchetioui commented on xla/service/gpu/runtime/dynamic_slice_thunk.cc
> +                       ->CloneToUnique();
Why do we need to clone to unique? Couldn't we just `move`?

2025-01-10 11:19 UTC, bchetioui commented on xla/service/gpu/runtime/dynamic_slice_thunk.cc
> +  static thread_local absl::flat_hash_map<DynamicSliceThunk*,
Am I correct that this design only works if there is a single offset we can calculate for each `DynamicSliceThunk`?

Presumably, we could have several `offset_modules` to evaluate per thunk, right?

If there is an invariant that we always have a single `offset_module` per `DynamicSliceThunk`, then this needs to be enforced somewhere and documented.

If not, then we need a test with several offset modules, and we need to make sure that this works.

2025-01-10 11:19 UTC, bchetioui commented on xla/service/gpu/fusions/fusions.h
> +                CallGraph& call_graph)
`const`? Seems like you store it as `const` anyway.

2025-01-13 18:04 UTC, shraiysh commented on xla/hlo/analysis/while_loop_analysis.cc
> +      /*cross_computation=*/false, /*inline_calls_and_fusions=*/true,
Yes, it is needed. Let me split it in a separate PR with a test so that it can be independently landed. The effect should be minimal though, and it should not cause any issues. The inline pass is run after the extraction, which should be very fast because the extracted module is small.

2025-01-13 18:54 UTC, shraiysh commented on xla/service/gpu/fusions/custom.cc
> +    op_ptr = callers[0];
Yes. That is the intent. Until we find the first while loop, we keep going to the parents.

2025-01-13 20:53 UTC, shraiysh commented on xla/service/gpu/runtime/dynamic_slice_thunk.cc
> +                                          std::unique_ptr<Literal>>
I tried that, but the same object in the memory is used by multiple threads. I think these threads correspond to the replicas but I am not too sure. Meaning, when the first replica increments the value, all the other replicas also see the new value, and this leads to inconsistency. This is similar to the work here: https://github.com/shraiysh/xla/blob/e27a06fe71dbecc79c2ee636abd4bf23755bd7d6/xla/service/gpu/runtime/while_thunk.cc#L48. Is there a better solution to this problem?

2025-01-13 22:06 UTC, shraiysh commented on xla/hlo/analysis/while_loop_analysis.cc
> +      /*cross_computation=*/false, /*inline_calls_and_fusions=*/true,
Moved it to #21375 (merged).

2025-01-13 22:07 UTC, shraiysh commented on xla/service/gpu/fusions/custom.cc
> +// offset is a function of the induction variable.
Added the checks.

2025-01-13 22:08 UTC, shraiysh commented on xla/service/gpu/fusions/custom.cc
> +// because we ensured this while creating this fusion.
Added checks here too. Thanks for pointing this out.

2025-01-13 22:09 UTC, shraiysh commented on xla/service/gpu/fusions/dynamic_slice_fusion_test.cc
> +  // Atleast two offsets: one for the input, and one for the outputs.
Changed to assert_eq

2025-01-13 22:10 UTC, shraiysh commented on xla/service/gpu/fusions/dynamic_slice_fusion_test.cc
> +  ErrorSpec error{1e-5, 1e-5};
Thanks for this, yes it should be 0.

2025-01-13 22:13 UTC, shraiysh commented on xla/service/gpu/runtime/dynamic_slice_thunk.cc
> +  static thread_local absl::flat_hash_map<DynamicSliceThunk*,
No, this works even if there are multiple offsets. Added test for that. There is only one "induction variable" per thunk. Because the surrounding while loop has to be the same, and so the induction variable has to be the same.

2025-01-13 22:15 UTC, shraiysh commented
Thank you for the detailed review @bchetioui. As the changes for `dynamic_slice_thunk.(cc|h)` have been split to #20794, I will be addressing those comments there. I have tried to address the remaining comments. Please let me know if I have missed something. Opening this for review again (changes except the ones in `dynamic_slice_thunk`.)

2025-01-13 22:45 UTC, shraiysh commented on xla/service/gpu/fusions/dynamic_slice_fusion_test.cc
> +      /*run_hlo_passes=*/false, /*use_threads=*/true, error);
Answered in a separate comment, where the check exists. (in this test)

2025-01-17 14:49 UTC, bchetioui commented on xla/service/gpu/runtime/dynamic_slice_thunk.cc
> +  static thread_local absl::flat_hash_map<DynamicSliceThunk*,
> No, this works even if there are multiple offsets. Added test for that. There is only one "induction variable" per thunk. Because the surrounding while loop has to be the same, and so the induction variable has to be the same.

But nothing guarantees that a loop has a single induction variable, right? We could be updating `offsets` based on different induction variables. Or what is it that would enforce the invariant that the offset is unique?

2025-01-17 18:27 UTC, shraiysh commented on xla/service/gpu/runtime/dynamic_slice_thunk.cc
> +  static thread_local absl::flat_hash_map<DynamicSliceThunk*,
> But nothing guarantees that a loop has a single induction variable, right?

There are checks for this. The dynamic slice fusion rewriter would not fuse this if there was no unique induction variable.

> what is it that would enforce the invariant that the offset is unique?

I am not sure I understand this, we are making sure that the offset is a function of the unique induction variable while fusing, and asserting this while lowering to avoid any correctness issues. Can you elaborate on this?

2025-01-21 17:22 UTC, bchetioui commented on xla/service/gpu/runtime/dynamic_slice_thunk.cc
> +  static thread_local absl::flat_hash_map<DynamicSliceThunk*,
> There are checks for this. The dynamic slice fusion rewriter would not fuse this if there was no unique induction variable ([here](https://github.com/shraiysh/xla/blob/15d9a6804c87ca29c3161c4765bf7bcab309406f/xla/service/gpu/transforms/dynamic_slice_fusion_rewriter.cc#L196))

Yeah, the point is that this is not enforced at all in the thunk---so in effect you are assuming here that things behave a certain way in another part of the pipeline, and that this behaviour will never change.

This assumption about how things work needs to be clearly documented in the thunk as well.

> I am not sure I understand this, we are making sure that the offset is a function of the unique induction variable while fusing, and asserting this while lowering to avoid any correctness issues. Can you elaborate on this?

Basically my concern is that we rely on assumed invariants that are not documented nor guaranteed to be upheld by any static mechanism locally. I.e., when we try to refactor/update this code later, it'll be hard to ensure correctness.

2025-01-21 17:43 UTC, shraiysh commented on xla/service/gpu/runtime/dynamic_slice_thunk.cc
> +  static thread_local absl::flat_hash_map<DynamicSliceThunk*,
> Yeah, the point is that this is not enforced at all in the thunk---so in effect you are assuming here that things behave a certain way in another part of the pipeline, and that this behaviour will never change.

This should be enforced by the code emitting the thunk. I have added checks for that [here](https://github.com/openxla/xla/blob/599fe492864e14b8811632cfa45c4f5bbd818e4e/xla/backends/gpu/codegen/custom.cc#L215). I don't know how we can enforce this within the thunk -- would it make sense for the thunk to accept a while operation, and check this itself, or would simply documenting this be enough? The fact that the thunk accepts only one `indvar_init` and `indvar_update` should force the user of this thunk to ensure that there is one induction variable, wouldn't it?

2025-02-03 17:58 UTC, shraiysh commented
Ping for review!

2025-02-07 17:42 UTC, shraiysh commented
Ping for review!

2025-02-10 16:14 UTC, bchetioui approved these changes

2025-02-11 08:44 UTC, bchetioui approved these changes

2025-02-13 13:28 UTC, closed without merging