Elementwise Ops in Collective Pipeliner
openxla/xla pull request #20399
Opened 2024-12-10 22:03 UTC by philipphack

Enables support for elementwise ops ahead of the dynamic-update-slice, such as in scaled FP8 GEMMs, in the collective pipeliner.

2024-12-18 14:55 UTC, frgossen requested changes
The change looks good but I'm not sure what the motivation is. Can you provide some benchmark numbers to show why this is beneficial? Is this useful for maxtext models?

2024-12-18 23:01 UTC, philipphack commented
@frgossen we found this in Paxml, but I think it could also be relevant elsewhere. Without this change, the scaling (i.e. multiplication) of the result of an FP8 dot prevents the pipelining of the collective. The graph in this case is dot -> all-reduce -> slice -> multiply -> dynamic-update-slice.

2025-01-22 15:54 UTC, frgossen commented
@philipphack , sorry for the delay. Do we have a concrete model to proof the performance gain here? Can you share the concrete PAXML config and the performance gains you observe?

2025-02-25 01:04 UTC, hx89 commented
@frgossen I have tested on PAXML Grok proxy FP8 model and verified the RS are pipelined correctly after the fix, and the e2e perf gain is about 14% over the run before the fix. So I think this PR is good to merge.

2025-03-05 15:08 UTC, frgossen approved these changes
Thanks!

2025-03-05 22:21 UTC, closed without merging