[gpu][ds-fusion] Add handling for offset module in ds-fusion thunk
openxla/xla pull request #20794
Opened 2024-12-20 22:02 UTC by shraiysh

This patch adds support for offset modules in ds fusion thunk. It also moves the `ResourceRequests` structure from `gpu_executable.cc` to `gpu_executable.h` because a valid implementation of the abstract class `Thunk::ResourceRequests` is required for calling `Thunk::Prepare()`.

This is split from #20332 as per request.

2024-12-28 16:52 UTC, shraiysh commented
The error in the CI job is unrelated. This PR is open for review.

2025-01-10 13:53 UTC, bchetioui requested changes
Thanks @shraiysh! @beckerhe suggested moving `ResourceRequests` to its own header and source files.

At its core, it seems like this PR does two things:

1. Reformulate the definitions of `ResourceRequests` such that they are accessible through the header file;
2. Add some functionality.

To be honest, from the current diff, it's not super straightforward to figure out what is what. Would you mind splitting the pure code move (that'll be a trivial review for us), and the added functionality?

2025-01-10 13:53 UTC, bchetioui commented on xla/service/gpu/gpu_executable.h
> +class ResourceRequests : public Thunk::ResourceRequests {
Let's maybe create dedicated source and header files for this class.

2025-01-13 22:39 UTC, shraiysh commented on xla/service/gpu/runtime/dynamic_slice_thunk.h
> +  using Offset = std::variant<int64_t, BufferAllocation::Slice, HloModule*>;
> Please update the docstring to account for this new variant constructor.

@bchetioui Added.

2025-01-13 22:40 UTC, shraiysh commented on xla/service/gpu/runtime/dynamic_slice_thunk.h
> +  std::vector<std::unique_ptr<HloModule>> extracted_offset_modules_;
> Let's find a better name than temp_modules_---that gives no explanation whatsoever as to what they contain. Does it refer to offsets as well? If so, maybe offset_modules is a better name here too?

Changed the names.

2025-01-13 22:41 UTC, shraiysh commented on xla/service/gpu/runtime/dynamic_slice_thunk.cc
> +Literal& Indvar(DynamicSliceThunk* thunk) {
> This deserves documentation.

I have added a comment explaining what it is, and also a reference to the same comment that the LoopCounters had. Hopefully that will be helpful.

2025-01-13 22:42 UTC, shraiysh commented on xla/service/gpu/runtime/dynamic_slice_thunk.cc
> +            HloEvaluator().Evaluate(**offset_module, {&Indvar(this)}));
> Why do we need to clone to unique? Couldn't we just move?

Yes, we can. Thanks. Changed this.

2025-01-13 23:05 UTC, shraiysh commented
Addressed comments from #20332. This is open for review now @bchetioui.

2025-01-21 17:18 UTC, shraiysh commented
Ping for review.

2025-01-21 17:41 UTC, bchetioui requested changes

2025-01-21 17:41 UTC, bchetioui commented on xla/backends/gpu/runtime/dynamic_slice_thunk.cc
> +Literal& Indvar(DynamicSliceThunk* thunk) {
These definitions are also in another change, where I commented on them & their documentation. Where should I review their introduction?

Either way, I'd like to see better documentations of why this is an appropriate implementation, and what this relies on :)

2025-01-21 17:41 UTC, bchetioui commented on xla/backends/gpu/runtime/dynamic_slice_thunk.cc
> +          std::move(indvar_update)) {  // Zip all arguments together to create a
Why is there a linefeed here? Seems like the comment should come on the line below :)

2025-01-21 17:41 UTC, bchetioui commented on xla/backends/gpu/runtime/dynamic_slice_thunk.cc
> +  if (indvar_init_ != nullptr) {
If this is nullable, should we make it `std::optional<std::unique_ptr<HloModule>>`? `nullptr` is not a value we expect to see everywhere, and it makes the API less clear imo.

2025-01-21 17:41 UTC, bchetioui commented on xla/backends/gpu/runtime/dynamic_slice_thunk.cc
> +  if (indvar_update_ != nullptr) {
Similar comment as above re. nullability.

2025-01-21 17:41 UTC, bchetioui commented on xla/backends/gpu/runtime/dynamic_slice_thunk.h
> +  // with induction variable as the input.
[a single] induction variable

2025-01-21 17:41 UTC, bchetioui commented on xla/backends/gpu/runtime/dynamic_slice_thunk.h
> +      std::vector<std::unique_ptr<HloModule>> extracted_offset_modules = {},
Should we have a `struct` wrapping these three vectors?

After all, they only exist together, or not at all.

2025-01-21 17:41 UTC, bchetioui commented on xla/backends/gpu/runtime/dynamic_slice_thunk.h
> +  // ownership with the thunk. The pointers to these offsets are stored in the
I don't really understand the comment about them being used. Presumably, we do use them somewhere? If not, why is it necessary to keep them alive?

2025-01-21 17:41 UTC, bchetioui commented on xla/backends/gpu/runtime/dynamic_slice_thunk.h
> +  // `indvar_update_` is a module of the prototype `(integer[]) -> integer[]`.
of the -> with

2025-01-21 17:41 UTC, bchetioui commented on xla/backends/gpu/runtime/dynamic_slice_thunk_test.cc
> +      /*temp_modules=*/std::move(fake_modules),
I guess this won't match the name, right? Thought we got rid of `temp_modules` :)

2025-01-21 17:41 UTC, bchetioui commented on xla/backends/gpu/runtime/dynamic_slice_thunk_test.cc
> +  ASSERT_EQ(dst, std::vector<float>({5 * 4 + 6 * 3 + 7 * 2 + 8 * 1}));
nit: `EXPECT_EQ`?

2025-01-21 17:41 UTC, bchetioui commented on xla/backends/gpu/runtime/dynamic_slice_thunk_test.cc
> +TEST_F(DynamicSliceThunkTest, TestOffsetAsAnModule) {
I think it's not clear what behaviour is being tested from this test name. How about something like `HostInductionVariableEvaluationExecutesCorrectly`?

2025-01-21 17:41 UTC, bchetioui commented on xla/backends/gpu/runtime/dynamic_slice_thunk_test.cc
> +TEST_F(DynamicSliceThunkTest, TestOffsetAsAnModule) {
What a long test :) but it looks reasonable.

2025-01-21 21:02 UTC, shraiysh reviewed
Addressed comments.

2025-01-23 08:49 UTC, bchetioui approved these changes
Thank you @shraiysh, this looks good!

2025-01-23 08:49 UTC, bchetioui commented on xla/backends/gpu/runtime/dynamic_slice_thunk.h
> +      CHECK(indvar_init_->entry_computation()->num_parameters() == 0)
nit: make a conditional that checks the output signatures as well?

Note: I'll LGTM to try to import the PR and avoid the back and forth since this is a nit comment, but would appreciate if you could make a tiny PR adding the checks :)

2025-01-23 08:49 UTC, bchetioui commented on xla/backends/gpu/runtime/dynamic_slice_thunk.h
> +  // This structure holds the metadata for offset computation on host. It stores
In your next tiny PR: "offset computation[s]"

2025-01-23 08:54 UTC, bchetioui approved these changes

2025-01-23 10:34 UTC, mooskagh commented on xla/backends/gpu/runtime/dynamic_slice_thunk.h
> +    std::unique_ptr<HloModule> indvar_init_, indvar_update_;
According to the style guide, struct member variables don't need trailing underscores (unlike class member variables).  

That was flagged by linter.

2025-01-23 17:50 UTC, shraiysh commented on xla/backends/gpu/runtime/dynamic_slice_thunk.h
> +    std::unique_ptr<HloModule> indvar_init_, indvar_update_;
Should I address this here or is this already in the process of merge and changes now will cause issues?

2025-01-24 22:29 UTC, mooskagh commented on xla/backends/gpu/runtime/dynamic_slice_thunk.h
> +    std::unique_ptr<HloModule> indvar_init_, indvar_update_;
I see that you've changed it.
That's indeed what I was asking, sorry for not being clear!

2025-01-24 22:30 UTC, mooskagh approved these changes

2025-01-27 13:34 UTC, bchetioui approved these changes

2025-01-28 15:00 UTC, closed without merging