[XLA GPU] fix pascal batched gemm numeric issues
openxla/xla pull request #3596
Opened 2023-06-14 08:15 UTC by Cjkkkk

2023-06-15 01:38 UTC, reedwm requested changes
Good catch!

The merge commit has some gemm_rewrite tests disable checking the HLO on pre-Volta, such as [here](https://github.com/openxla/xla/blob/bd068e0f8954b63b91fa98df8b6ce6884eec0f5c/xla/service/gpu/tests/gemm_rewrite_test.cc#L1763-L1764). Can you remove this checks?

2023-06-20 20:10 UTC, Cjkkkk commented
> Good catch!
> 
> The merge commit has some gemm_rewrite tests disable checking the HLO on pre-Volta, such as [here](https://github.com/openxla/xla/blob/bd068e0f8954b63b91fa98df8b6ce6884eec0f5c/xla/service/gpu/tests/gemm_rewrite_test.cc#L1763-L1764). Can you remove this checks?

Thanks, I forgot to remove these in the tests. Removed now.

2023-06-20 22:45 UTC, reedwm approved these changes

2023-06-22 21:50 UTC, reedwm approved these changes

2023-06-26 16:39 UTC, ddunl commented on xla/service/gpu/gemm_rewriter.cc
seems like `cuda_compute_capability_` is unused now, we should delete it I think

2023-06-26 19:41 UTC, reedwm commented on xla/service/gpu/gemm_rewriter.cc
Yep, the internal linter is complaining about this so we cannot submit until it's deleted.

2023-06-26 20:48 UTC, Cjkkkk commented on xla/service/gpu/gemm_rewriter.cc
thanks for the reminder, removed now.

2023-06-26 20:50 UTC, ddunl commented
I think needs a rebase as well because I'm seeing some complaints about conflicts on the CI

2023-06-27 17:32 UTC, Cjkkkk commented
> I think needs a rebase as well because I'm seeing some complaints about conflicts on the CI

rebased now. should be good.

2023-06-27 17:47 UTC, reedwm approved these changes

2023-06-27 20:18 UTC, closed without merging