Introducing lhlo lowering logic for fused mha.
openxla/xla pull request #4019
Opened 2023-07-05 05:19 UTC by Tixxx

This pr contains changes to lower lhlo fused mha custom call to cudnnFMHA thunk and runner for both forward and backward fmha calls.

2023-07-11 17:15 UTC, cheshire requested changes
Could we add tests?

2023-07-11 17:15 UTC, cheshire commented on xla/stream_executor/dnn.cc
>      const dnn::TensorDescriptor& output_descriptor,
Could SE changes be separated out?

2023-07-11 17:23 UTC, cheshire commented on xla/service/gpu/ir_emitter_unnested.cc
> +      break;
Extraneous "break", here and below.

2023-07-11 17:26 UTC, cheshire commented on xla/service/gpu/gpu_fused_mha_runner.cc
> +  if (params.config->fmha_scale) scale = *params.config->fmha_scale;
Code style prefers braces everywhere

2023-07-11 17:31 UTC, cheshire commented on xla/service/gpu/gpu_fused_mha_runner.cc
> +    double &dropout_rate = *config.dropout_rate;
I'm assuming config.dropout_rate = backend_config.dropout_rate() does not work?

2023-07-11 19:08 UTC, Tixxx commented on xla/service/gpu/gpu_fused_mha_runner.cc
> +  if (params.config->fmha_scale) scale = *params.config->fmha_scale;
changed

2023-07-18 16:54 UTC, cheshire approved these changes

2023-07-19 19:42 UTC, closed without merging