Fix the matchReductionComputation function to also consider fused to_apply region of collectives
openxla/xla pull request #6126
Opened 2023-10-06 05:01 UTC by Tixxx

Improve matchReductionComputation to match for fusion case if it's used after fusion pass. Also consider optional converts if it's used after bf16 normalization pass.

2023-10-06 05:13 UTC, jurahul commented
My overall comment is that we have this kind of matching in other places as well (somewhere in XLA/GPU runtime lowering) and the ideal solution here is to leave the bf16 computation attached to all-reduce/reduce-scatter as is during promotion so we don't have to look through this fusion in other places.

2023-10-06 05:49 UTC, Tixxx commented
> My overall comment is that we have this kind of matching in other places as well (somewhere in XLA/GPU runtime lowering) and the ideal solution here is to leave the bf16 computation attached to all-reduce/reduce-scatter as is during promotion so we don't have to look through this fusion in other places.

Yea, currently this only happens in float normalization but I feel this type of promotion can happen anywhere and this issue might come back some time in the future. For now I can look into float normalization to prevent it from promoting collectives' called computations. But I'm thinking if there's a more explicit way to do this, something like giving collective instructions another field called unmutable_called_computation which is read-only so their called_computations is empty therefore won't be modified.

2023-10-06 21:13 UTC, Tixxx commented
> My overall comment is that we have this kind of matching in other places as well (somewhere in XLA/GPU runtime lowering) and the ideal solution here is to leave the bf16 computation attached to all-reduce/reduce-scatter as is during promotion so we don't have to look through this fusion in other places.

@jurahul  I changed float normalization to not promote to_apply regions of collectives. Let me know if this would make more sense than the first commit. Thanks.

2023-10-09 16:56 UTC, jurahul requested changes
I agree that this change can be done first. I think it might be better to split the HLO computation changes and float normalization changes into 2 separate PRs.

2023-10-09 17:09 UTC, Tixxx commented on xla/service/float_normalization_test.cc
> +  auto module = CreateNewVerifiedModule();
Agreed, i thought about it but all tests in this file are following this pattern(including some of the existing tests that contain collectives) so I didnt want to break the style.

2023-10-09 17:20 UTC, Tixxx commented on xla/service/float_normalization_test.cc
> +class TestFloatNoComputeSupport : public FloatSupport {
the class TestFloatSupport supports some elementwise compute ops to be low precision but doesnt support collectives, that's actually not the case we wanted. We would need a floatSupport class that doesn't support elementwise compute ops but supports collective ops to repro the issue. That's why I created a new class based on `FloatSupport`.
I will remove some redundant code in this class that wont be needed by the use-case of this class and put some comments on top of the class.

2023-10-09 18:17 UTC, Tixxx commented
> I agree that this change can be done first. I think it might be better to split the HLO computation changes and float normalization changes into 2 separate PRs.

Sure, I have extracted out the hlo computation changes and created a separate pr, https://github.com/openxla/xla/pull/6171.
Could you help review that? I will rebase this one after the above is merged.

2023-10-10 23:33 UTC, jurahul approved these changes

2023-10-11 18:05 UTC, frgossen approved these changes
Thanks!

2023-10-11 19:21 UTC, ddunl approved these changes
Copybara not picking up on other reviews for some reason...

2023-10-11 21:37 UTC, closed without merging

2023-10-12 13:38 UTC, frgossen commented
The breakage is an HLO shape mismatch after float-normalization. I will try to get you more info on this

2023-10-12 19:00 UTC, Tixxx commented
> The breakage is an HLO shape mismatch after float-normalization. I will try to get you more info on this

@frgossen Thanks for the heads-up. If you have a snippet of the erroneous hlo, that would be great.