[ROCM] rocm 6.0 fixes followup
openxla/xla pull request #7277
Opened 2023-11-24 19:58 UTC by pemeliya

This is a follow-up PR for rocm-6.0 platform support.
I have also adapted two unit tests which were failing on specific architectures / platform version.

@xla-rotation: would you take a look, please?

2023-11-26 19:49 UTC, ezhulenev approved these changes

2023-11-27 07:08 UTC, akuegel requested changes

2023-11-27 07:08 UTC, akuegel commented on xla/stream_executor/device_description.h
> +  };
The linter is complaining about the ";" character in this line.
Also it is complaining that there is no newline after the last line in this file.

2023-11-27 09:26 UTC, akuegel approved these changes

2023-11-27 10:20 UTC, pemeliya commented
@ddunl JAX Linux GPU build seems to fail due to some configuration problem.. perhaps the build should be restarted?

2023-11-27 19:07 UTC, ddunl commented
Not sure what happened on those last runs, I hadn't seen that before, looks good now that it re-ran

2023-11-27 23:13 UTC, closed without merging

2023-11-28 16:23 UTC, pemeliya commented
@ddunl : it seems that not all changes have been merged, particularly, I don't see these ones in the upstream:
https://github.com/openxla/xla/pull/7277/files#diff-710053e487634d28f9fbe5c4ee69dae088a90bc525d2e3cb8af81dabf640fc27R89-R90

https://github.com/openxla/xla/pull/7277/files#diff-710053e487634d28f9fbe5c4ee69dae088a90bc525d2e3cb8af81dabf640fc27R89-R90

Could it be that because these changes reside in third_party subdirectory, they were missed somehow ?

2023-11-28 16:55 UTC, ddunl commented
That's likely, I'll have a change rectifying this today. Thanks for pointing this out!!