[XLA:GPU] Enhance cuDNN fused attention rewriter patttern match with num of users check
openxla/xla pull request #7331
Opened 2023-11-28 16:21 UTC by Cjkkkk

Follow up PR for https://github.com/openxla/xla/pull/7016.

Enhance current fused attention rewriter pattern match by adding more checks for num of users of matched nodes. For example, for softmax sub pattern like `sub(x, reduce_max(x))`, we want to make sure `sub` and `reduce_max` node has exactly one user, therefore no softmax nodes will be left in the graph after softmax is replaced with cudnn fused attention custom call.

1. We add checks for all functional nodes that we pattern match in the rewriter. For example, in pattern bmm1-bias-softmax-bmm2, for softmax, it would be sub/reduce/divide/exp nodes and for bias add, it would be add node. For each of these nodes, it should either have exactly one user or less than or equal two users if it could be used by backwards.
2. Remove some back to back optional convert.
3. Add some functions in pattern match to easily check num of users(`WithNumUser()` and `WithLeNumUser()`)
4. Turning on FMHA feature by default.

2023-11-28 18:24 UTC, Cjkkkk commented
@akuegel Hi Adrian, this is the follow up PR for https://github.com/openxla/xla/pull/7016 as we discussed last week.

2023-11-28 19:31 UTC, Cjkkkk commented
is this test `Int8GemmRankGreaterThanTwo` expected to fail? @akuegel

2023-11-28 21:26 UTC, Cjkkkk commented
seems like file check issue. Fixed with a generic name.

2023-11-28 21:30 UTC, Cjkkkk commented
Not sure why https://github.com/openxla/xla/commit/0e01a692222c041f2703e6c113e92991b1e80d61 changes this test file check.

2023-11-29 08:47 UTC, akuegel commented
> Not sure why [0e01a69](https://github.com/openxla/xla/commit/0e01a692222c041f2703e6c113e92991b1e80d61) changes this test file check.

When enabling the FMHA pipeline, it effectively means that we will do Layout normalization before running GemmRewriterTriton, and before it was done after GemmRewriterTriton. This can affect test expectations in this test, as those are End2End tests.

2023-11-29 08:54 UTC, akuegel requested changes
I am fine with enabling the flag in the same PR, but I just want to warn that in case a rollback is needed, it could happen that the whole change is rolled back instead of just the flag flip. This is possibly outside my control, as the rollback request would most likely happen (and be approved) outside my working hours.

2023-11-29 08:54 UTC, akuegel commented on xla/service/pattern_matcher.h
> +    *os << "which has less than or euqal " << user_num_
nit: euqal -> equal

2023-11-29 08:54 UTC, akuegel commented on xla/service/pattern_matcher.h
> +  explicit constexpr HloInstructionPatternLeNumUserImpl(
nit: maybe rename and use AtMost instead of Le ?

2023-11-29 08:54 UTC, akuegel commented on xla/service/pattern_matcher.h
> +  constexpr auto WithLeNumUser(int64_t user_num) const {
AtMost instead of Le?

2023-11-29 18:40 UTC, AyanmoI commented
> I am fine with enabling the flag in the same PR, but I just want to warn that in case a rollback is needed, it could happen that the whole change is rolled back instead of just the flag flip. This is possibly outside my control, as the rollback request would most likely happen (and be approved) outside my working hours.

Sure let's do that and create a separate PR.

2023-11-29 18:41 UTC, Cjkkkk commented
> I am fine with enabling the flag in the same PR, but I just want to warn that in case a rollback is needed, it could happen that the whole change is rolled back instead of just the flag flip. This is possibly outside my control, as the rollback request would most likely happen (and be approved) outside my working hours.

I will move enabling the flag into a separate PR.

2023-11-30 07:46 UTC, akuegel approved these changes

2023-12-01 22:03 UTC, ezhulenev commented
Fails in internal CI with: 

```
[third_party/tensorflow/compiler/xla/service/gpu/cudnn_fused_mha_rewriter_test.cc:3334](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/xla/service/gpu/cudnn_fused_mha_rewriter_test.cc?l=3334&ws=tap-presubmit-server/133418086&snapshot=2):25: error: unused variable 'fmha' [-Werror,-Wunused-variable]
 3334 |   const HloInstruction* fmha;
      |                         ^~~~
[third_party/tensorflow/compiler/xla/service/gpu/cudnn_fused_mha_rewriter_test.cc:3384](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/xla/service/gpu/cudnn_fused_mha_rewriter_test.cc?l=3384&ws=tap-presubmit-server/133418086&snapshot=2):25: error: unused variable 'fmha' [-Werror,-Wunused-variable]
 3384 |   const HloInstruction* fmha;
      |                         ^~~~
[third_party/tensorflow/compiler/xla/service/gpu/cudnn_fused_mha_rewriter_test.cc:3473](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/xla/service/gpu/cudnn_fused_mha_rewriter_test.cc?l=3473&ws=tap-presubmit-server/133418086&snapshot=2):25: error: unused variable 'fmha' [-Werror,-Wunused-variable]
 3473 |   const HloInstruction* fmha;
      |                         ^~~~
3 errors generated.
```

2023-12-02 07:07 UTC, Cjkkkk commented
> Fails in internal CI with:
> 
> ```
> [third_party/tensorflow/compiler/xla/service/gpu/cudnn_fused_mha_rewriter_test.cc:3334](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/xla/service/gpu/cudnn_fused_mha_rewriter_test.cc?l=3334&ws=tap-presubmit-server/133418086&snapshot=2):25: error: unused variable 'fmha' [-Werror,-Wunused-variable]
>  3334 |   const HloInstruction* fmha;
>       |                         ^~~~
> [third_party/tensorflow/compiler/xla/service/gpu/cudnn_fused_mha_rewriter_test.cc:3384](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/xla/service/gpu/cudnn_fused_mha_rewriter_test.cc?l=3384&ws=tap-presubmit-server/133418086&snapshot=2):25: error: unused variable 'fmha' [-Werror,-Wunused-variable]
>  3384 |   const HloInstruction* fmha;
>       |                         ^~~~
> [third_party/tensorflow/compiler/xla/service/gpu/cudnn_fused_mha_rewriter_test.cc:3473](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/xla/service/gpu/cudnn_fused_mha_rewriter_test.cc?l=3473&ws=tap-presubmit-server/133418086&snapshot=2):25: error: unused variable 'fmha' [-Werror,-Wunused-variable]
>  3473 |   const HloInstruction* fmha;
>       |                         ^~~~
> 3 errors generated.
> ```

should be fixed now.

2023-12-04 08:56 UTC, akuegel approved these changes

2023-12-04 17:54 UTC, Cjkkkk commented
seems still some internal checks failed. Could anyone shares some info on this?

2023-12-05 07:06 UTC, closed without merging