[XLA:CPU] [oneDNN] Adding support for MatMul + BiasAdd fusion with oneDNN custom call rewrite
openxla/xla pull request #7484
Opened 2023-12-02 00:33 UTC by mahmoud-abuzaina

This PR enables OneDNN library call for the matched XLA HLO MatMul + BiasAdd patterns through custom_call instruction. In particular, this PR:

1. Renames oneDNN matmul rewriter pass and moves it after layout assignment pass.
2. Enables transposed input support for oneDNN matmul
3. Enables MatMul + BiasAdd pattern matching with oneDNN rewrite
4. Adds multiple tests with different variations of MatMul + BiasAdd pattern

2023-12-06 13:08 UTC, penpornk approved these changes
Approving since @d0k already approved the original PR.

2023-12-06 13:09 UTC, penpornk requested changes
Oops sorry I approved the wrong PR. Undoing the approve for now.

2023-12-06 19:39 UTC, penpornk requested changes
Thank you for adding many test cases!

2023-12-08 21:26 UTC, mahmoud-abuzaina commented on xla/service/cpu/backend_config.proto
> -  repeated FusionKind fused_ops = 3;
Fixed.

2023-12-08 21:28 UTC, mahmoud-abuzaina commented on xla/service/cpu/cpu_compiler.cc
> +#endif  // INTEL_MKL && ENABLE_ONEDNN_V3
Right, I think we just need once before the Matmul pass to simplify the shape. I removed the redundant one.

2023-12-08 21:28 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_matmul_rewriter.cc
> +auto IntermediateAllowedInstructions(HloInstruction** bitcast,
Done.

2023-12-08 21:28 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_matmul_rewriter.cc
> +auto ConvertPattern(HloInstruction** instr) {
Done.

2023-12-08 21:29 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_matmul_rewriter.cc
> +bool AllOperandsConvertedFromBF16ToF32(const HloInstruction* instr) {
I tagged few those functions as inline.

2023-12-08 21:30 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_matmul_rewriter.cc
> +      // For addened, match one of these patterns:
Fixed.

2023-12-08 21:30 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_matmul_rewriter.cc
> +      bool bias_broad = Match(addend, nonscalar_broadcast);
Done.

2023-12-08 21:35 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_matmul_rewriter.cc
I tried to use "git mv" earlier, it did not work because the changes are relatively big in that file so git insists to mark the relevant files as deleted/new. I also tried (after your review) to do rename & code changes in two separate commits to force git to recognize the rename but it still marked them as new/deleted eventually. I will give it another try and push another commit if it works.

2023-12-08 21:36 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_matmul_rewriter.cc
> +  if (!should_rewrite) return false;
Done.

2023-12-08 21:36 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_matmul_rewriter.cc
> +  }
Done.

2023-12-08 21:36 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_matmul_rewriter.cc
> +    bool transpose_b = (rhs_dim_k == rhs_shape.rank() - 2) ? false : true;
Done.

2023-12-08 21:36 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_matmul_rewriter.cc
> +      // (new-custom-call -> bitcast). Also, this will be followd by -> convert
Fixed.

2023-12-08 21:36 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_matmul_rewriter.cc
> +  // library. Matched hlo instruction(s) are replaced by custom call.
Fixed.

2023-12-08 21:36 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_matmul_rewriter.h
> +// This pass pattern-matches hlo dot instructions and rewrites into custom
Fixed.

2023-12-08 21:37 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_util.h
> +  using namespace tsl::port;
Fixed by resolving merge conflicts.

2023-12-08 21:37 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_util.h
Done.

2023-12-08 21:39 UTC, mahmoud-abuzaina commented on xla/tests/onednn_matmul_test.cc
> +  const char* fused_matmul_bias = R"(
Fixed.

2023-12-08 21:39 UTC, mahmoud-abuzaina commented on xla/tests/onednn_matmul_test.cc
> +  )");
Done.

2023-12-08 21:41 UTC, mahmoud-abuzaina commented
Thank you @penpornk for the review. I have addressed your comments except for the "git mv" one. Please see my comment above about that. If I fix it I will push another commit.

2023-12-11 20:31 UTC, mahmoud-abuzaina commented on xla/service/cpu/onednn_matmul_rewriter.cc
I could not fix this branch probably because of the commits in between. I created a replacement PR with same changes https://github.com/openxla/xla/pull/7681, even though git still shows deleted/new file in the new PR diff but history seems to be still maintained for this file.

2023-12-13 18:27 UTC, penpornk commented on xla/service/cpu/onednn_matmul_rewriter.cc
Got it. Thank you very much for your efforts, @mahmoud-abuzaina! I've approved PR  https://github.com/openxla/xla/pull/7681.

2023-12-13 18:29 UTC, closed without merging