[GPU] NCCL User Buffer Registration - Add CollectiveMemoryAllocate using ncclMemAlloc to SE (2/3)
openxla/xla pull request #7962
Opened 2023-12-20 19:15 UTC by trevor-m

Main PR here: https://github.com/openxla/xla/pull/7843

2023-12-26 17:25 UTC, cheshire requested changes

2023-12-26 17:25 UTC, cheshire commented on xla/stream_executor/gpu/gpu_driver.h
> +  static void* CollectiveMemoryAllocate(GpuContext* context, uint64_t bytes);
Maybe return Status and error out on unsupported platforms? I know it's not consistent with the rest of the file, but we're trying to get there.

2024-01-03 15:16 UTC, PatriosTheGreat approved these changes

2024-01-03 20:03 UTC, ddunl approved these changes

2024-01-05 09:55 UTC, closed without merging