Adding driver APIs for unified stream ordered allocation implementation
openxla/xla pull request #8513
Opened 2024-01-16 18:25 UTC by weihanmines

This commit is served as preparation for a later PR which will implement an unified driver interface of stream ordered memory allocation for both CUDA and ROCm. The current implementation `gpu_cudamallocaysnc_allocator.cc ` is platform dependent. This PR pulls out the driver APIs from the source file `gpu_cudamalloasync_allocator.cc`, puts a set of APIs in the class ` GpuDriver`, and add platform dependent implementation in corresponding directories (cuda and rocm) like other driver APIs. 

Another way to implement this is adding preprocessors in `gpu_cudamalloasync_allocator.cc`. May I ask which way is preferred for adding this functionality to ROCm? Your comments are appreciated.
`

2024-01-19 11:18 UTC, i-chaochen commented
@xla-rotation I think something wrong on the CI infra and it's not related to our changes. Could you review this PR, please? Thanks

2024-02-13 04:23 UTC, kamaljeeti commented
Hi @cheshire, can you look into this once? Thanks.

2024-02-26 10:52 UTC, kamaljeeti commented
Hi @ddunl , could you please review  this PR? Thank you!

2024-03-18 12:47 UTC, cheshire commented
I thought `gpu_cudamallocaysnc_allocator.cc` isn't used anywhere by default yet?

2024-03-18 12:49 UTC, cheshire requested changes

2024-03-18 12:49 UTC, cheshire commented on xla/stream_executor/cuda/cuda_driver.cc
> +        absl::StrFormat("Failed to get CUDA pool attribute: %s", ToString(res)));
Could we use a helper macro?

2024-03-18 12:49 UTC, cheshire commented on xla/stream_executor/rocm/rocm_driver.cc
> +    LOG(INFO) << "failed to allocate "
Same nit: could we use a helper macro? Maybe ideally return StatusOr<void*>?

2024-03-18 14:20 UTC, i-chaochen commented
Hi @cheshire thanks for the feedback.

I'm sorry due to some reasons we have to withdraw this PR. Is it possible you can close this one? We will resubmit this later in another PR.

2024-03-20 15:39 UTC, tdanyluk commented
I close it based on @i-chaochen's request.

2024-03-20 15:39 UTC, closed without merging