[XLA:CPU] Matmul + mul handling with OneDnn eltwise_linear.
openxla/xla pull request #8583
Opened 2024-01-18 10:33 UTC by jmaksymc

This PR enables OneDNN call for the matched XLA HLO MatMul+Linear pattern using custom_call instruction. This PR:

* Enables MatMul+Linear pattern matching
* Using OneDNN MatMul post-ops handles MatMul+Linear fusion
* Adds a test for MatMul + Linear pattern

2024-01-23 06:23 UTC, kamaljeeti commented
Hi @penpornk , can you look into this once? Thanks.

2024-01-24 14:44 UTC, penpornk requested changes
Thank you for the PR and sorry for the delay!

2024-01-24 17:36 UTC, jmaksymc commented on xla/service/cpu/backend_config.proto
> +  // Because od proto failing for specific decimal values,
Hi, I'm currently on leave and will open an issue with an example when I'm back (01.30).

2024-01-30 14:31 UTC, penpornk approved these changes
Since the requested change is trivial and the author is OOO, I'll pull this in and make the changes internally.

2024-01-30 15:26 UTC, closed without merging

2024-01-31 15:13 UTC, jmaksymc commented on xla/service/cpu/backend_config.proto
> +  // Because od proto failing for specific decimal values,
@penpornk Here is an issue related to this problem: https://github.com/openxla/xla/issues/9010. Please let me know if you need more details.