GpuTimer: take Stream not GpuStream
openxla/xla pull request #9841
Opened 2024-02-22 17:20 UTC by olupton

This is split out from https://github.com/openxla/xla/pull/9757 on request from @cheshire.

It changes the `GpuTimer` constructor (and factory) signature to take `Stream*` instead of `GpuStream*`. All call sites were converting Stream* to GpuStream* in order to construct GpuTimer, so the call site transformations are all trivial.

This allows the other changes in https://github.com/openxla/xla/pull/9757 to take advantage of some higher-level helpers (`CreateTypedKernel`, `ThenLaunch`) in the implementation of `GpuTimer`.

2024-02-22 17:33 UTC, cheshire approved these changes

2024-02-23 10:24 UTC, thomasjoerg requested changes

2024-02-23 10:24 UTC, thomasjoerg commented
@klucke who is refactoring this part of the codebase to take a look at this PR too.

2024-02-23 10:51 UTC, olupton commented on xla/stream_executor/gpu/gpu_timer.h
> +                                                                bool is_needed);
I searched in JAX but didn't find anything. Are you referring to something internal?
But sure, I can make this PR only add the new signature. It won't be straightforward to benefit from the accuracy improvements in https://github.com/openxla/xla/pull/9757 inside the old signature though.

2024-02-23 12:34 UTC, olupton commented on xla/stream_executor/gpu/gpu_timer.h
> +                                                                bool is_needed);
I re-added the old signatures (with `[[deprecated]]`) in 4c5878b60dca1e299ab6c5785e6ebb730f86301e.

2024-02-23 12:43 UTC, cheshire commented on xla/stream_executor/gpu/gpu_timer.h
> +                                                                bool is_needed);
@thomasjoerg Could you link to the usages? I couldn't find them either.

2024-02-23 12:47 UTC, thomasjoerg commented on xla/stream_executor/gpu/gpu_timer.h
> +                                                                bool is_needed);
Here for instance:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/bias_op.cc#L490

2024-02-23 13:49 UTC, thomasjoerg approved these changes

2024-02-23 15:55 UTC, closed without merging

2024-02-23 16:43 UTC, olupton commented on xla/stream_executor/gpu/gpu_timer.h
> +                                                                bool is_needed);
@thomasjoerg will you take care of updating the other usages you're aware of and removing the [[deprecated]] overloads?